program Pyme_Fact;

uses
  Forms,
  PymeFact in 'PymeFact.pas' {FrmInicio},
  Tools in 'Tools.pas',
  Unit1 in 'Unit1.pas' {frmLogin},
  Unit3 in 'Unit3.pas' {FrmCliente},
  Unit4 in 'Unit4.pas' {FrmPrincipal},
  Unit5 in 'Unit5.pas' {FrmArticulos},
  Unit7 in 'Unit7.pas' {FrmCodBar},
  Unit8 in 'Unit8.pas' {Frmfacturacion},
  Unit9 in 'Unit9.pas' {FrmCobrar},
  Unit11 in 'Unit11.pas' {FrmGet_cobro},
  Unit12 in 'Unit12.pas' {FrmEmpleados},
  Unit13 in 'Unit13.pas' {FrmCunsulta_Precio},
  Unit14 in 'Unit14.pas' {FmrMant_Categoria},
  Unit15 in 'Unit15.pas' {frmcuadre_caja},
  Unit16 in 'Unit16.pas' {FrmCxC},
  Unit17 in 'Unit17.pas' {Frm_Control_Fact},
  Unit18 in 'Unit18.pas' {FrmGet_CXC},
  Unit20 in 'Unit20.pas' {FrmCatProducto},
  Unit21 in 'Unit21.pas' {FrmFact},
  Unit23 in 'Unit23.pas' {FrmCombo},
  variables in 'variables.pas',
  Unit24 in 'Unit24.pas' {frmConduce1},
  Unit25 in 'Unit25.pas' {FrmUsuario},
  Unit26 in 'Unit26.pas' {FrmBuscarArticulos},
  Unit27 in 'Unit27.pas' {frmCat},
  Unit28 in 'Unit28.pas' {FrmAjuste},
  Unit29 in 'Unit29.pas' {FrmProvee},
  Unit30 in 'Unit30.pas' {frmMantCombo},
  Unit31 in 'Unit31.pas' {frmConsultaFact},
  Unit32 in 'Unit32.pas' {FrmAdmInventario},
  Unit33 in 'Unit33.pas' {FrmTurno},
  Unit34 in 'Unit34.pas' {FrmDescarga},
  Unit35 in 'Unit35.pas' {Fupdate},
  Unit36 in 'Unit36.pas' {FrmCGastos},
  Unit37 in 'Unit37.pas' {FrmGastos},
  Unit38 in 'Unit38.pas' {FrmCaja},
  Unit39 in 'Unit39.pas' {frmNC},
  Unit40 in 'Unit40.pas' {Notas_Credito},
  Unit41 in 'Unit41.pas' {FrmRVentas},
  Unit42 in 'Unit42.pas' {FrmComision},
  Unit43 in 'Unit43.pas' {FrmConfig},
  Unit44 in 'Unit44.pas' {FrmUnidad},
  Unit45 in 'Unit45.pas' {FrmConsultaArticulos},
  Unit46 in 'Unit46.pas' {FrmRebajaPRecio},
  Unit48 in 'Unit48.pas' {FrmMAntArticulos},
  Unit49 in 'Unit49.pas',
  Unit50 in 'Unit50.pas' {FrmRxProveedor},
  Unit51 in 'Unit51.pas' {FrmGustos},
  Unit52 in 'Unit52.pas' {FrmMturnos},
  Unit2 in 'Unit2.pas' {datos: TDataModule},
  Unit53 in 'Unit53.pas' {FrmPartionamiento},
  Unit22 in 'Unit22.pas' {FrmNFact},
  Unit55 in 'Unit55.pas' {FrmRMecanciaInvManual},
  Unit56 in 'Unit56.pas' {FrmBuscarProveedores},
  Unit57 in 'Unit57.pas' {FrmBuscarCategoria},
  Unit58 in 'Unit58.pas' {FrmPedido},
  Unit60 in 'Unit60.pas' {FrmRVFecha},
  Unit47 in 'Unit47.pas' {FrmCobro},
  Unit61 in 'Unit61.pas' {FrmConsultaSuplidores},
  Unit62 in 'Unit62.pas' {FrmPAss},
  Unit64 in 'Unit64.pas' {Combiotaza},
  Unit65 in 'Unit65.pas' {FrmCompras},
  Unit66 in 'Unit66.pas' {FrmBuscarCompras},
  Unit67 in 'Unit67.pas' {FrmCambioPrecio},
  Unit68 in 'Unit68.pas' {FrmHold},
  Unit70 in 'Unit70.pas' {FrmRma},
  Unit71 in 'Unit71.pas' {FrmConsulta_Proveedor},
  Unit72 in 'Unit72.pas' {FrmVendedores},
  Unit73 in 'Unit73.pas' {FrmRutas},
  Unit74 in 'Unit74.pas' {FrmBuscarPedido},
  Unit75 in 'Unit75.pas' {PackingList},
  Unit76 in 'Unit76.pas' {FrmNotaCF},
  Unit77 in 'Unit77.pas' {FrmReporteVentaxVendedor},
  Unit78 in 'Unit78.pas' {FrmRCompraXClientes},
  Unit79 in 'Unit79.pas' {FrmLabelgarantia},
  Unit80 in 'Unit80.pas' {FrmCotiza},
  Unit81 in 'Unit81.pas' {FRProductosVendidos},
  Unit82 in 'Unit82.pas' {FrmDetalleEfectivo},
  Unit83 in 'Unit83.pas' {RTopMenu},
  Unit84 in 'Unit84.pas' {FrmResetTablas},
  Unit85 in 'Unit85.pas' {FrmPagosRealizados},
  Unit86 in 'Unit86.pas' {FrmConsultaConduce},
  Unit87 in 'Unit87.pas' {FrmDGII},
  Unit88 in 'Unit88.pas' {FrmModulos},
  Unit89 in 'Unit89.pas' {FrmAlmacenes},
  Unit90 in 'Unit90.pas' {FrmComprobanteEmitidos},
  Unit91 in 'Unit91.pas' {FrmConsultaNotaC},
  Unit92 in 'Unit92.pas' {FrmConsultaPagosxClientes},
  Unit93 in 'Unit93.pas' {FrmRepInventario},
  Unit94 in 'Unit94.pas' {DataUtil: TDataModule},
  Unit95 in 'Unit95.pas' {licencia},
  Unit96 in 'Unit96.pas' {FrmComisionServicios},
  Unit97 in 'Unit97.pas' {FrmMoneda},
  Unit98 in 'Unit98.pas' {FrmBuscarMoneda},
  Unit99 in 'Unit99.pas' {FrmMantBancos},
  Unit100 in 'Unit100.pas' {FrmTransaciones},
  Unit101 in 'Unit101.pas' {FrmBtransaciones},
  Unit102 in 'Unit102.pas' {FrmBCtasBancos},
  Unit103 in 'Unit103.pas' {FrmBalanceBanco},
  Unit104 in 'Unit104.pas' {FrmArticulosBuscar},
  Unit105 in 'Unit105.pas' {FrmActualizaBalanceCXC},
  Unit106 in 'Unit106.pas' {FrmConsultasFxPagar},
  Unit107 in 'Unit107.pas' {FrmConsultaCliente},
  Unit108 in 'Unit108.pas' {FrmBProveedor},
  Unit109 in 'Unit109.pas' {FrmBuscaAlmacen},
  Unit110 in 'Unit110.pas' {FrmTiposEquipos},
  Unit111 in 'Unit111.pas' {Rma},
  Unit112 in 'Unit112.pas' {FConsultaArtiRMA},
  Unit113 in 'Unit113.pas' {FrmConduce},
  Unit114 in 'Unit114.pas' {FrmConsultaFacturas},
  Unit115 in 'Unit115.pas' {FrmConduceAdmin},
  Unit116 in 'Unit116.pas' {FrmDetalleFact},
  Unit117 in 'Unit117.pas' {FAutorizacion},
  Unit118 in 'Unit118.pas' {FrmBuscarInstalador},
  Unit119 in 'Unit119.pas' {FrmBackup},
  Unit120 in 'Unit120.pas' {FrmServicioInstalador},
  Unit121 in 'Unit121.pas' {FrmControlNCF},
  Unit123 in 'Unit123.pas' {FrmNotario},
  UInicio in 'UInicio.pas' {FrmHome},
  FactNo in 'FactNo.pas' {FrmNFact_normal1},
  Unit125 in 'Unit125.pas' {FrmComsionFactura},
  Unit124 in 'Unit124.pas' {FrmSeries},
  Unit126 in 'Unit126.pas' {ComprobantesAnulados},
  Unit122 in 'Unit122.pas' {FNotificacion},
  Unit127 in 'Unit127.pas' {FrmUpSecuencia},
  Unit128 in 'Unit128.pas' {FrmDecomisos},
  Unit129 in 'Unit129.pas' {FrmReporte_Inventario},
  Unit130 in 'Unit130.pas' {FrmHolder},
  Pizeria in 'Pizeria.pas' {FrmPizeria},
  USabores in 'USabores.pas' {FrmClasificaciones},
  Unit131 in 'Unit131.pas' {FrmIngredientes},
  Unit132 in 'Unit132.pas' {FrmGetIngredientes},
  UFinder in 'UFinder.pas' {FrmFinder},
  UMesas in 'UMesas.pas' {FrmMesas},
  Unit133 in 'Unit133.pas' {FrmDelivery},
  Unit134 in 'Unit134.pas' {FrmPedidosCocina},
  UfraccionPiza in 'UfraccionPiza.pas' {FrmFraccionPiza},
  UFacturasImpresas in 'UFacturasImpresas.pas' {FrmFacturasImpresas},
  Unit135 in 'Unit135.pas' {FrmEditarNCF},
  Unit136 in 'Unit136.pas' {FrmImportarExcel},
  UMiData in 'UMiData.pas' {MiData: TDataModule},
  UopcionCaja in 'UopcionCaja.pas' {FrmOpcionCaja},
  UAperturaCaja in 'UAperturaCaja.pas' {FrmAperturaCaja},
  uCobroFact in 'uCobroFact.pas' {FrmCobroFact},
  UAdmProductos in 'UAdmProductos.pas' {FrmAdmProducto},
  UActualizaDiasCredito in 'UActualizaDiasCredito.pas' {FrmActualizaDiasCredito},
  UBuscaCliente in 'UBuscaCliente.pas' {FrmBuscaCliente},
  UFacturaProv in 'UFacturaProv.pas' {FrmFactProveedores},
  UCobroFactCxP in 'UCobroFactCxP.pas' {FrmCobroCXP},
  UConsultaFactCXP in 'UConsultaFactCXP.pas' {FrmConsultaFactCXP},
  UEstadoCXP in 'UEstadoCXP.pas' {FrmEstadoCxp},
  UAdminArticulos in 'UAdminArticulos.pas' {FrmAdminArticulos},
  UhistoricoProductos in 'UhistoricoProductos.pas' {FrmHistoricoMovmientoInventario},
  UFactRapida in 'UFactRapida.pas' {FrmFactRapida},
  UHistoricosCostos in 'UHistoricosCostos.pas' {FrmHistoricosCostos},
  UcajerroAnterior in 'UcajerroAnterior.pas' {FrmCajerosAnteriores},
  UReporteCXC in 'UReporteCXC.pas' {FrmReporteCXC},
  UentradaCredito in 'UentradaCredito.pas' {FrmEntradaCreditos},
  URCreditoxfechas in 'URCreditoxfechas.pas' {FrmRCreditoxFechas},
  Unit137 in 'Unit137.pas' {FrmCorteInventario},
  UEliminaMOvimiento in 'UEliminaMOvimiento.pas' {FrmEliminaMovimiento},
  UReporteVxP in 'UReporteVxP.pas' {FrmVentasXproductos},
  UActualizaCosto in 'UActualizaCosto.pas' {FActualizaCosto},
  UFindArticulos in 'UFindArticulos.pas' {FrmFindArticulos},
  UBuscarUsuarios in 'UBuscarUsuarios.pas' {FBuscarUsuarios},
  Urtc in 'Urtc.pas' {Frtc},
  UCierreInventarioCubos in 'UCierreInventarioCubos.pas' {FCierreInventarioCubos},
  UAperturaCuadreCubos in 'UAperturaCuadreCubos.pas' {FAperturaCuadreCubos},
  UPagoSolidaridad in 'UPagoSolidaridad.pas' {FSolidaridadPago},
  Vcl.Themes,
  Vcl.Styles,
  UinventarioDirecto in 'UinventarioDirecto.pas' {FInventarioDirecto},
  UInventarioEquivalencia in 'UInventarioEquivalencia.pas' {FInventarioEquivalencia},
  UIngredientes in 'UIngredientes.pas' {FGetIngredientes},
  uDIngredientes in 'uDIngredientes.pas' {FIngredientes},
  uCocina in 'uCocina.pas' {fPedidosCocina},
  UCard in 'UCard.pas' {Form138},
  uDetalleCocina in 'uDetalleCocina.pas' {FdetalleCocina1},
  UgetCorteInventario in 'UgetCorteInventario.pas' {fGetCorteInventario},
  ImpresionDirecto in 'ImpresionDirecto.pas',
  USelectorPrinters in 'USelectorPrinters.pas' {FSelectorPrinter},
  udataprint in 'udataprint.pas' {DataPrint: TDataModule},
  uAutorizaBoss in 'uAutorizaBoss.pas' {fAutorizacionBoss},
  UREcontero in 'UREcontero.pas' {FReconteo},
  UDetalleCocina1 in 'UDetalleCocina1.pas' {FDetalleCocina},
  touch in 'touch.pas' {FrmTouch},
  Udescuento in 'Udescuento.pas' {FDescuento},
  FReporteRestaurant in 'FReporteRestaurant.pas' {FReporteResturant},
  uMd5 in 'Class\uMd5.pas',
  uDetalleMesa in 'uDetalleMesa.pas' {fDetalleMesas},
  UEquivalencia in 'UEquivalencia.pas' {FrmEquivalencia},
  uBuscarArticulosMayor in 'uBuscarArticulosMayor.pas' {FFindArticulosMayor},
  Uimpuestos in 'Uimpuestos.pas' {fImpuestos},
  uCentral in 'uCentral.pas' {fCentral},
  routers in 'Class\routers.pas',
  uLoginAPP in 'uLoginAPP.pas' {Form139},
  uVentanaAviso in 'uVentanaAviso.pas' {fMensages},
  uInventario_Master in 'Inventarios\uInventario_Master.pas' {fInventario_Master},
  UbuscarArticulos in 'UbuscarArticulos.pas' {fBuscarArticulos},
  uBuscarSubCategoria in 'uBuscarSubCategoria.pas' {fBuscarSubCategoria},
  UImpuesto in 'UImpuesto.pas' {form_01},
  uSubCategoria in 'uSubCategoria.pas' {FSubCategoria},
  uBuscarSubCategorias in 'uBuscarSubCategorias.pas' {fuBuscarSubCategorias},
  usustancia in 'usustancia.pas' {Fsustancia},
  uBuscarSustancia in 'uBuscarSustancia.pas' {fBuscarSustancia},
  Umarca in 'Umarca.pas' {fMarca},
  uBuscarMarcas in 'uBuscarMarcas.pas' {fBuscarMarcas},
  uindicacionez in 'uindicacionez.pas' {fIndicaciones},
  uBuscarIndicaciones in 'uBuscarIndicaciones.pas' {FBuscarIndicaciones},
  uclasificacion in 'uclasificacion.pas' {fClasificacion},
  UbuscarClasificacion in 'UbuscarClasificacion.pas' {fBuscarClasificacion},
  uBuscarProveedores in 'uBuscarProveedores.pas' {fBuscarProveedores},
  UBuscarImpuesto in 'UBuscarImpuesto.pas' {FbuscarImpuesto},
  uLotes in 'uLotes.pas' {fLotes},
  uAjusteDirecto in 'uAjusteDirecto.pas' {fAjusteDirecto},
  uConsultarLote in 'uConsultarLote.pas' {fConsultarLotes},
  uinventario_lote in 'uinventario_lote.pas' {FInventarioLote},
  uBuscarFiltros in 'uBuscarFiltros.pas' {FbuscarFiltro},
  Ustart in 'Ustart.pas' {FStart},
  uGetSesion in 'uGetSesion.pas' {FGetSession},
  uPerfilUsuario in 'uPerfilUsuario.pas' {fPerfirUsuario},
  uLotesVencimiento in 'uLotesVencimiento.pas' {fLoteVencimiento},
  UReporteInvenario in 'UReporteInvenario.pas' {ReporteInventario},
  Unit59 in 'Unit59.pas',
  uReinicioInventario in 'uReinicioInventario.pas' {fReinicioInventario};

{$R *.res}

 begin
  Application.Initialize;
  Application.CreateForm(TFrmHome, FrmHome);
  Application.CreateForm(TFrmInicio, FrmInicio);
  Application.CreateForm(Tdatos, datos);
  Application.CreateForm(TFAutorizacion, FAutorizacion);
  Application.CreateForm(TFNotificacion, FNotificacion);
  Application.CreateForm(TFrmHolder, FrmHolder);
  Application.CreateForm(TMiData, MiData);
  Application.CreateForm(TFrmReporteCXC, FrmReporteCXC);
  Application.CreateForm(TFrmRutas, FrmRutas);
  Application.CreateForm(TFrmVendedores, FrmVendedores);
  Application.CreateForm(TFrmEntradaCreditos, FrmEntradaCreditos);
  Application.CreateForm(TFrmRCreditoxFechas, FrmRCreditoxFechas);
  Application.CreateForm(TFrmEliminaMovimiento, FrmEliminaMovimiento);
  Application.CreateForm(TFrmVentasXproductos, FrmVentasXproductos);
  Application.CreateForm(TFActualizaCosto, FActualizaCosto);
  Application.CreateForm(TFrmBuscarMoneda, FrmBuscarMoneda);
  Application.CreateForm(TFrmFindArticulos, FrmFindArticulos);
  Application.CreateForm(TFBuscarUsuarios, FBuscarUsuarios);
  Application.CreateForm(TFRProductosVendidos, FRProductosVendidos);
  Application.CreateForm(TFrtc, Frtc);
  Application.CreateForm(TFCierreInventarioCubos, FCierreInventarioCubos);
  Application.CreateForm(TFAperturaCuadreCubos, FAperturaCuadreCubos);
  Application.CreateForm(TFSolidaridadPago, FSolidaridadPago);
  Application.CreateForm(TFInventarioDirecto, FInventarioDirecto);
  Application.CreateForm(TFInventarioEquivalencia, FInventarioEquivalencia);
  Application.CreateForm(TForm138, Form138);
  Application.CreateForm(TFSelectorPrinter, FSelectorPrinter);
  Application.CreateForm(TDataPrint, DataPrint);
  Application.CreateForm(TFReconteo, FReconteo);
  Application.CreateForm(TFGetIngredientes, FGetIngredientes);
  Application.CreateForm(TFDetalleCocina, FDetalleCocina);
  Application.CreateForm(TFDescuento, FDescuento);
  Application.CreateForm(TfDetalleMesas, fDetalleMesas);
  Application.CreateForm(TfCentral, fCentral);
  Application.CreateForm(TForm139, Form139);
  Application.CreateForm(TfLoteVencimiento, fLoteVencimiento);
  Application.Run;
end.
