unit Unit2;

interface

uses
   SysUtils, Classes, Controls, Forms,
  WideStrings, DBXFirebird, DB, SqlExpr, FMTBcd, ZAbstractRODataset, ZDataset,
  ZConnection, ZAbstractTable, ZAbstractDataset, ZSqlUpdate, ZIBEventAlerter,
  ZAbstractConnection, AdvToolBar, AdvToolBarStylers;

type
  Tdatos = class(TDataModule)
    Data: TZConnection;
    IbqEmpleados: TZReadOnlyQuery;
    IbqEmpleadosCOD_EMP: TWideStringField;
    IbqEmpleadosNOMBRES_EMP: TWideStringField;
    IbqEmpleadosDIRECCION: TWideStringField;
    IbqEmpleadosCEDULA: TWideStringField;
    IbqEmpleadosTELEFONO: TWideStringField;
    IbqEmpleadosCELULAR: TWideStringField;
    IbqEmpleadosTIPO: TWideStringField;
    IbqEmpleadosLOGIN: TWideStringField;
    IbqEmpleadosPIN: TWideStringField;
    IbqEmpleadosMODIFICAR_ARTICULOS: TWideStringField;
    IbqEmpleadosELIMINAR: TWideStringField;
    IbqEmpleadosIMPRIMIR: TWideStringField;
    IbqEmpleadosCONTABILIDAD: TWideStringField;
    IbqEmpleadosMODIFICAR_FACTURAS: TWideStringField;
    IbqEmpleadosMODIFICAR_UTILIDAD: TWideStringField;
    IbqEmpleadosIMPRIMIR_CUADRE: TWideStringField;
    IbqEmpleadosIMPRIMIR_FINACIERO: TWideStringField;
    IbqEmpleadosCOD_EMP1: TIntegerField;
    IbqEmpleadosdescmax: TFloatField;
    IbqEmpleadosINICIO: TDateField;
    IbqEmpleadosSUELDO: TFloatField;
    IbqEmpleadosCOD: TIntegerField;
    IbqEmpleadosCARGO: TWideStringField;
    IbqEmpleadosFECHA_ING: TDateField;
    ZQuery1: TZQuery;
    IbClientes: TZUpdateSQL;
    DsClientes: TDataSource;
    ZUpdateSQL1: TZUpdateSQL;
    FbtClientes: TZQuery;
    FbtClientesCODIGO: TIntegerField;
    FbtClientesDIRECCION: TWideStringField;
    FbtClientesCEDULA: TWideStringField;
    FbtClientesTELEFONO: TWideStringField;
    FbtClientesCELULAR: TWideStringField;
    FbtClientesCOLOR: TWideStringField;
    FbtClientesCONTACTO: TWideStringField;
    FbtClientesTXTCNF: TWideStringField;
    FbtClientesCREDITOLIMITE: TFloatField;
    FbtClientesRNC: TWideStringField;
    FbtClientesCONDICION: TWideStringField;
    FbtClientesINICIO: TDateField;
    FbtClientesSUELDO: TFloatField;
    FbtClientesPAGOITB: TWideStringField;
    FbtClientesCREDITO: TWideStringField;
    FbtClientesBALANCE: TFloatField;
    FbtClientesESTADO: TWideStringField;
    FbtClientesMOVIL: TWideStringField;
    FbtClientesCODIGO_T: TWideStringField;
    FqArticulos: TZQuery;
    FUArticulos: TZUpdateSQL;
    FqArticulosMODELO: TWideStringField;
    FqArticulosMARCA: TWideStringField;
    FqArticulosCOLOR: TWideStringField;
    FqArticulosCATEGORIA: TWideStringField;
    FqArticulosCANT_MINI: TFloatField;
    FqArticulosSERIE: TWideStringField;
    FqArticulosALMACEN: TWideStringField;
    FqArticulosPRECIO1: TFloatField;
    FqArticulosPRECIO2: TFloatField;
    FqArticulosCOSTO: TFloatField;
    FqArticulosPROVEEDOR1: TWideStringField;
    FqArticulosPROVEEDOR2: TWideStringField;
    FqArticulosIMPUESTO: TFloatField;
    FqArticulosITBIS: TWideStringField;
    FqArticulosABREVIADO1: TWideStringField;
    FqArticulosUNIDAD_VENTA: TWideStringField;
    FqArticulosCODIGO1: TWideStringField;
    FqArticulosMODIFUSUARIO: TWideStringField;
    FqArticulosFECHAMODI: TDateField;
    FqArticulosABREVIADO: TWideStringField;
    FqArticulosPOLITICA: TWideStringField;
    FqArticulosCODIGOXTR: TIntegerField;
    FqArticulosTIPOCOD: TWideStringField;
    FqArticulosESTADO: TWideStringField;
    FqArticulosCANTIDAD_MAXIMA: TFloatField;
    FqArticulosCOD1: TIntegerField;
    FqArticulosIMAGEN: TBlobField;
    FqArticulosTIPO: TWideStringField;
    FqArticulosBENEF: TFloatField;
    FqArticulosBENEF_PORC: TWideStringField;
    FqArticulosPRECIOABIERTO: TWideStringField;
    FqArticulosCOD_ART1: TIntegerField;
    FqArticulosCOCINA: TWideStringField;
    FqArticulosCLA_COSTO: TWideStringField;
    FqArticulosCLA_PRECIO: TWideStringField;
    IbqCategorias: TZQuery;
    DsCategoria: TDataSource;
    FbqFabricantes: TZQuery;
    FUfabricantes: TZUpdateSQL;
    FbqMaster_Fact: TZQuery;
    FRMaster_Fact: TZUpdateSQL;
    ZUconfiguracion: TZReadOnlyQuery;
    ZUconfiguracionCODIGO_COM: TWideStringField;
    ZUconfiguracionEMPRESA: TWideStringField;
    ZUconfiguracionRNC: TWideStringField;
    ZUconfiguracionTELEFONO: TWideStringField;
    ZUconfiguracionFAX: TWideStringField;
    ZUconfiguracionCELULAR: TWideStringField;
    ZUconfiguracionEMAIL: TWideStringField;
    ZUconfiguracionCONTACTO: TWideStringField;
    ZUconfiguracionFACTIMPRIME: TWideStringField;
    ZUconfiguracionGENERART: TWideStringField;
    ZUconfiguracionITBIS: TFloatField;
    ZUconfiguracionAVG_GANANCIA: TFloatField;
    ZUconfiguracionCOBRAR_ITBS: TWideStringField;
    ZUconfiguracionTHEMS: TWideStringField;
    ZUconfiguracionANCHO: TIntegerField;
    ZUconfiguracionALTO: TIntegerField;
    ZUconfiguracionRUTABACKUP: TWideStringField;
    ZUconfiguracionABRIRCAJON: TIntegerField;
    ZUconfiguracionPTINTERTPV: TWideStringField;
    ZUconfiguracionCARGO_CARD: TFloatField;
    ZUconfiguracionCARGO_CHEQUE: TFloatField;
    ZUconfiguracionMSN_PIE_FACT: TWideStringField;
    ZUconfiguracionIMP_CANT: TWideStringField;
    ZUconfiguracionIMPRIMIRCREDITO: TWideStringField;
    ZUconfiguracionIMPRIMIRCONTADO: TWideStringField;
    ZUconfiguracionDESCUENTO: TWideStringField;
    ZUconfiguracionTIPOITBS: TWideStringField;
    ZUconfiguracionTERMINAL: TWideStringField;
    ZUconfiguracionSTOPVENTAS: TFloatField;
    ZUconfiguracionSTOPCOMPRAS: TFloatField;
    ZUconfiguracionCONTROLSTOPVENTAS: TWideStringField;
    ZUconfiguracionCONTROLSTOPCOMPRAS: TWideStringField;
    ZUconfiguracionNCF_CF_INICIO_NUMERO: TFloatField;
    ZUconfiguracionNCF_CF_INICIO_LETRA: TWideStringField;
    ZUconfiguracionNCF_CF_CONTADOR: TIntegerField;
    ZUconfiguracionNCF_CF_FINAL_NUMERO: TFloatField;
    ZUconfiguracionNCF_VF_INICIO_NUMERO: TFloatField;
    ZUconfiguracionNCF_VF_INICIO_LETRA: TWideStringField;
    ZUconfiguracionNCF_VF_CONTADOR: TIntegerField;
    ZUconfiguracionNCF_VF_FINAL_NUMERO: TFloatField;
    ZUconfiguracionNCF_ESP_INICIO_NUMERO: TFloatField;
    ZUconfiguracionNCF_ESP_INICIO_LETRA: TWideStringField;
    ZUconfiguracionNCF_ESP_CONTADOR: TIntegerField;
    ZUconfiguracionNCF_ESP_FINAL: TFloatField;
    ZUconfiguracionNO_AUTORIZACION2: TFloatField;
    ZUconfiguracionNO_AUTORIZACION3: TFloatField;
    ZUconfiguracionNO_AUTORIZACION: TFloatField;
    ZUconfiguracionUSAR_CF: TWideStringField;
    ZUconfiguracionUSAR_VF: TWideStringField;
    ZUconfiguracionUSAR_ESP: TWideStringField;
    ZUconfiguracionROTULO_FC: TWideStringField;
    ZUconfiguracionROTULO_FVF: TWideStringField;
    ZUconfiguracionROTULO_ESP: TWideStringField;
    ZUconfiguracionVARIABLE_DEDUCIBLE: TFloatField;
    ZUconfiguracionLOGO: TBlobField;
    ZUconfiguracionCLAVEANULAR: TWideStringField;
    ZUconfiguracionTERMINAL_TPV: TWideStringField;
    ZUconfiguracionMONTOCF: TFloatField;
    ZUconfiguracionREDONDEAR: TWideStringField;
    DsMaster_Fact: TDataSource;
    Zdetalle: TZQuery;
    QueryUpdate: TZQuery;
    QCAJA: TZIBEventAlerter;
    FqArticulosCODIGO: TWideStringField;
    ZEmpleados: TZQuery;
    Zupdate_empleado: TZUpdateSQL;
    ZEmpleadosCOD_EMP: TWideStringField;
    ZEmpleadosNOMBRES_EMP: TWideStringField;
    ZEmpleadosDIRECCION: TWideStringField;
    ZEmpleadosCEDULA: TWideStringField;
    ZEmpleadosTELEFONO: TWideStringField;
    ZEmpleadosCELULAR: TWideStringField;
    ZEmpleadosTIPO: TWideStringField;
    ZEmpleadosLOGIN: TWideStringField;
    ZEmpleadosPIN: TWideStringField;
    ZEmpleadosMODIFICAR_ARTICULOS: TWideStringField;
    ZEmpleadosELIMINAR: TWideStringField;
    ZEmpleadosIMPRIMIR: TWideStringField;
    ZEmpleadosCONTABILIDAD: TWideStringField;
    ZEmpleadosMODIFICAR_FACTURAS: TWideStringField;
    ZEmpleadosMODIFICAR_UTILIDAD: TWideStringField;
    ZEmpleadosIMPRIMIR_CUADRE: TWideStringField;
    ZEmpleadosIMPRIMIR_FINACIERO: TWideStringField;
    ZEmpleadosCOD_EMP1: TIntegerField;
    ZEmpleadosINICIO: TDateField;
    ZEmpleadosSUELDO: TFloatField;
    ZEmpleadosCOD: TIntegerField;
    ZEmpleadosCARGO: TWideStringField;
    ZEmpleadosFECHA_ING: TDateField;
    DsEmpleados: TDataSource;
    ZUCategoria: TZUpdateSQL;
    FbCategorias: TZQuery;
    Zrecibo_pago: TZQuery;
    Zup_recibo_pago: TZUpdateSQL;
    DsZup_recibo_pago: TDataSource;
    Zrecibo_pagoNO_RECIBO1: TIntegerField;
    Zrecibo_pagoNO_RECIBO: TWideStringField;
    Zrecibo_pagoFECHA: TDateField;
    Zrecibo_pagoCOD_CLIENTE: TWideStringField;
    Zrecibo_pagoCLIENTE: TWideStringField;
    Zrecibo_pagoMONTO: TFloatField;
    Zrecibo_pagoLETRAS1: TWideStringField;
    Zrecibo_pagoTIPO: TWideStringField;
    Zrecibo_pagoDESCRIPCION: TWideStringField;
    FqArticulosCOMENTARIO: TWideMemoField;
    ZuManArti: TZUpdateSQL;
    MantArt: TZQuery;
    MantArtCOD_ART: TIntegerField;
    MantArtMODELO: TWideStringField;
    MantArtMARCA: TWideStringField;
    MantArtCOLOR: TWideStringField;
    MantArtCOD_CAT: TIntegerField;
    MantArtCOD_SERIE: TIntegerField;
    F: TIntegerField;
    MantArtCOSTO: TFloatField;
    MantArtCOD_PROV1: TIntegerField;
    MantArtEXISTENCIA1: TFloatField;
    MantArtABREVIADO: TWideStringField;
    MantArtCOD_BARRA: TWideStringField;
    MantArtCOD_UV: TIntegerField;
    MantArtUSUARIOMOD: TIntegerField;
    MantArtFECHA_MOD: TDateField;
    MantArtPOLITICA: TWideStringField;
    MantArtCOSTO_PR: TFloatField;
    MantArtIMAGEN: TBlobField;
    MantArtCLA_COSTO: TWideStringField;
    MantArtCLA_PRECIO: TWideStringField;
    MantArtPRECIO_A: TFloatField;
    MantArtPRECIO_B: TFloatField;
    MantArtPRECIO_D: TFloatField;
    MantArtCODIGOTXT: TWideStringField;
    MantArtESTADO: TIntegerField;
    ZUseries: TZUpdateSQL;
    Series: TZQuery;
    SeriesCOD_SERIES: TIntegerField;
    SeriesCOD_ARTI: TIntegerField;
    SeriesSERIES: TWideStringField;
    SeriesESTADO: TIntegerField;
    ZUAlmacen: TZUpdateSQL;
    Malmacen: TZQuery;
    MantArtEXTFOTO: TWideStringField;
    FbCategoriasCODCAT: TIntegerField;
    ZUCombo: TZUpdateSQL;
    ZCombo: TZQuery;
    ZComboCOD_MANCOMBO: TIntegerField;
    ZComboCOD_ART: TIntegerField;
    ZComboPRECIO: TFloatField;
    DsArt: TDataSource;
    ZComboARTICULO: TWideStringField;
    ZComboCOSTO: TFloatField;
    ZComboCOSTO_PR: TFloatField;
    ZUMaCombo: TZUpdateSQL;
    MaCombo: TZQuery;
    MaComboCOMBOMASTER: TIntegerField;
    MaComboNOMBRECOMBO: TWideStringField;
    MaComboPRECIO1: TFloatField;
    MaComboCOSTOS1: TFloatField;
    MaComboCOSTOS2: TFloatField;
    MaComboESTADO: TIntegerField;
    MaComboCODTIENDA: TIntegerField;
    MaComboDESCRIPCION: TWideStringField;
    DsMaCombo: TDataSource;
    ZComboMACOMBOID: TIntegerField;
    MaComboCODIGOTXT: TWideStringField;
    tienda: TZQuery;
    Zutienda: TZUpdateSQL;
    tiendaTIENDAID: TIntegerField;
    tiendaESTADO: TIntegerField;
    DsTienda: TDataSource;
    ZComboPRECIO2: TFloatField;
    ZComboPRECIO3: TFloatField;
    MaComboPRECIO2: TFloatField;
    MaComboPRECIO3: TFloatField;
    ZUMconduce: TZUpdateSQL;
    ZMConduce: TZQuery;
    DsMconduce: TDataSource;
    ZUInventario: TZUpdateSQL;
    ZInventario: TZQuery;
    ZInventarioMINVENTARIOID: TIntegerField;
    ZInventarioFECHA: TDateField;
    ZInventarioIDTIENDA: TIntegerField;
    ZInventarioCOD_ART: TIntegerField;
    ZInventarioCONCEPTOID: TIntegerField;
    ZInventarioCOD_USUARIO: TIntegerField;
    ZInventarioENTRADA: TFloatField;
    ZInventarioSALIDA: TFloatField;
    tiendaDIRECCCION: TWideStringField;
    tiendaCIUDAD: TWideStringField;
    tiendaTELEFONO1: TWideStringField;
    tiendaTELEFONO2: TWideStringField;
    tiendaRNC: TWideStringField;
    zuUsuario: TZUpdateSQL;
    ZUsaurios: TZQuery;
    ZEmpleadosTIENDAID: TIntegerField;
    ZEmpleadosESTADOS: TIntegerField;
    ZqUsuarios: TZReadOnlyQuery;
    tiendaDESCRIPCION: TWideStringField;
    ZMConduceMCONDUCEID: TIntegerField;
    ZMConduceMCONDUCETXT: TWideStringField;
    ZMConduceFECHA: TDateField;
    ZMConduceUSUARIOID: TIntegerField;
    ZMConduceTIENDAID: TIntegerField;
    ZMConduceTIENDAIDDESTINO: TIntegerField;
    ZMConduceESTADO: TIntegerField;
    ZMConduceDESCRIPCION: TWideStringField;
    FbtClientesRENGLONCNF: TWideStringField;
    FbqMaster_FactNO_FACT: TIntegerField;
    FbqMaster_FactFECHA_FAC: TDateField;
    FbqMaster_FactTIPO: TWideStringField;
    FbqMaster_FactCOD_CLIENT: TWideStringField;
    FbqMaster_FactCOD_EMP: TWideStringField;
    FbqMaster_FactNO_FACT1: TWideStringField;
    FbqMaster_FactMONTO: TFloatField;
    FbqMaster_FactHORA: TTimeField;
    FbqMaster_FactPOGXITBS: TFloatField;
    FbqMaster_FactTIPOPAGO: TWideStringField;
    FbqMaster_FactMONTOPAGO: TFloatField;
    FbqMaster_FactCONDICION: TWideStringField;
    FbqMaster_FactRENTA: TWideStringField;
    FbqMaster_FactCODIGO: TIntegerField;
    FbqMaster_FactTIPOITBS: TWideStringField;
    FbqMaster_FactVENDEDOR: TWideStringField;
    FbqMaster_FactSITUACION: TWideStringField;
    FbqMaster_FactNCF: TWideStringField;
    FbqMaster_FactRNC_CLIENTE: TWideStringField;
    FbqMaster_FactNCF1: TFloatField;
    FbqMaster_FactNOM_CLIENTE: TWideStringField;
    FbqMaster_FactDESCUENTO: TFloatField;
    FbqMaster_FactROTULO: TWideStringField;
    FbqMaster_FactNO_AUTORIZA_NCF: TFloatField;
    FbqMaster_FactMONTOFINANCIADO: TFloatField;
    FbqMaster_FactCUOTAS: TIntegerField;
    FbqMaster_FactINTERES: TFloatField;
    FbqMaster_FactPAGADO: TFloatField;
    FbqMaster_FactLEYPROPINA: TFloatField;
    FbqMaster_FactCOMPROBANTE: TWideStringField;
    FbqMaster_FactTERMINAL: TWideStringField;
    FbqMaster_FactEFECTIVO: TFloatField;
    FbqMaster_FactDEVOLUCION1: TFloatField;
    FbqMaster_FactRESTANTE: TFloatField;
    FbqMaster_FactABONO: TFloatField;
    FbqMaster_FactCHEK: TWideStringField;
    FbqMaster_FactNO_RECIBO: TIntegerField;
    FbqMaster_FactPAGADOCXC: TFloatField;
    FbqMaster_FactMESES: TIntegerField;
    FbqMaster_FactDIAS: TIntegerField;
    FbqMaster_FactPENDIENTE: TFloatField;
    FbqMaster_FactESTADOPAGO: TWideStringField;
    FbqMaster_FactDEVOLUCION: TFloatField;
    FbqMaster_FactCONDICION_PAGO: TIntegerField;
    FbqMaster_FactCOMBO: TWideStringField;
    FbqMaster_FactCOBRADO: TIntegerField;
    FbqMaster_FactQUEES: TWideStringField;
    FbqMaster_FactUSUARIOID: TIntegerField;
    FbqMaster_FactCLIENTEID: TIntegerField;
    FbqMaster_FactCLIENTENOMBRE: TWideStringField;
    FbqMaster_FactNOMBRES_EMP: TWideStringField;
    ZdetalleNO_FACT: TIntegerField;
    ZdetalleNO_FACT1: TWideStringField;
    ZdetalleMASTERID: TIntegerField;
    ZdetalleCANTIDAD: TFloatField;
    ZdetallePRECIO: TFloatField;
    ZdetalleIMPUESTO: TFloatField;
    ZdetalleITBS: TFloatField;
    ZdetalleITBIS2: TFloatField;
    ZdetalleCOD_ART: TWideStringField;
    ZdetalleCOMBO: TWideStringField;
    ZdetalleARTICULOID: TIntegerField;
    DsDetalleMaster: TDataSource;
    ZdetalleARTICULO: TWideStringField;
    zdetalle1: TZTable;
    zdetalle1NO_FACT: TIntegerField;
    zdetalle1NO_FACT1: TWideStringField;
    zdetalle1FECHA_FACT: TDateField;
    zdetalle1TIPO: TWideStringField;
    zdetalle1COD_EMP: TWideStringField;
    zdetalle1ARTICULO: TWideStringField;
    zdetalle1MARCA: TWideStringField;
    zdetalle1MODELO: TWideStringField;
    zdetalle1CANTIDAD: TFloatField;
    zdetalle1PRECIO: TFloatField;
    zdetalle1IMPUESTO: TFloatField;
    zdetalle1ITBS: TFloatField;
    zdetalle1ITBIS2: TFloatField;
    zdetalle1TOTAL: TFloatField;
    zdetalle1DESC1: TFloatField;
    zdetalle1COD_ART: TWideStringField;
    zdetalle1ITB: TWideStringField;
    zdetalle1COBROITB: TWideStringField;
    zdetalle1UNID: TWideStringField;
    zdetalle1COSTOS: TFloatField;
    zdetalle1ESTADO: TWideStringField;
    zdetalle1TIPOITBS: TWideStringField;
    zdetalle1ABREVIADO: TWideStringField;
    zdetalle1IMPORTE: TFloatField;
    zdetalle1COD_CLIENT: TIntegerField;
    zdetalle1DESCUENTO: TFloatField;
    zdetalle1COMBO: TWideStringField;
    zdetalle1CONDICION_ART: TWideStringField;
    zdetalle1LINEA: TIntegerField;
    zdetalle1OPIT: TIntegerField;
    zdetalle1PRECIO1: TFloatField;
    zdetalle1EMPLEADO: TWideStringField;
    zdetalle1CANT: TFloatField;
    zdetalle1TURNO: TIntegerField;
    zdetalle1CLAVE_COSTO: TWideStringField;
    ZUpdateSQL2: TZUpdateSQL;
    Configuracion: TZQuery;
    DataSource1: TDataSource;
    ConfiguracionCODIGO_COM: TWideStringField;
    ConfiguracionEMPRESA: TWideStringField;
    ConfiguracionRNC: TWideStringField;
    ConfiguracionTELEFONO: TWideStringField;
    ConfiguracionFAX: TWideStringField;
    ConfiguracionCELULAR: TWideStringField;
    ConfiguracionEMAIL: TWideStringField;
    ConfiguracionCONTACTO: TWideStringField;
    ConfiguracionFACTIMPRIME: TWideStringField;
    ConfiguracionGENERART: TWideStringField;
    ConfiguracionITBIS: TFloatField;
    ConfiguracionAVG_GANANCIA: TFloatField;
    ConfiguracionCOBRAR_ITBS: TWideStringField;
    ConfiguracionTHEMS: TWideStringField;
    ConfiguracionANCHO: TIntegerField;
    ConfiguracionALTO: TIntegerField;
    ConfiguracionRUTABACKUP: TWideStringField;
    ConfiguracionABRIRCAJON: TIntegerField;
    ConfiguracionPTINTERTPV: TWideStringField;
    ConfiguracionCARGO_CARD: TFloatField;
    ConfiguracionCARGO_CHEQUE: TFloatField;
    ConfiguracionIMP_CANT: TWideStringField;
    ConfiguracionIMPRIMIRCREDITO: TWideStringField;
    ConfiguracionIMPRIMIRCONTADO: TWideStringField;
    ConfiguracionDESCUENTO: TWideStringField;
    ConfiguracionTIPOITBS: TWideStringField;
    ConfiguracionTERMINAL: TWideStringField;
    ConfiguracionSTOPVENTAS: TFloatField;
    ConfiguracionSTOPCOMPRAS: TFloatField;
    ConfiguracionCONTROLSTOPVENTAS: TWideStringField;
    ConfiguracionCONTROLSTOPCOMPRAS: TWideStringField;
    ConfiguracionNCF_CF_INICIO_NUMERO: TFloatField;
    ConfiguracionNCF_CF_INICIO_LETRA: TWideStringField;
    ConfiguracionNCF_CF_CONTADOR: TIntegerField;
    ConfiguracionNCF_CF_FINAL_NUMERO: TFloatField;
    ConfiguracionNCF_VF_INICIO_NUMERO: TFloatField;
    ConfiguracionNCF_VF_INICIO_LETRA: TWideStringField;
    ConfiguracionNCF_VF_CONTADOR: TIntegerField;
    ConfiguracionNCF_VF_FINAL_NUMERO: TFloatField;
    ConfiguracionNCF_ESP_INICIO_NUMERO: TFloatField;
    ConfiguracionNCF_ESP_INICIO_LETRA: TWideStringField;
    ConfiguracionNCF_ESP_CONTADOR: TIntegerField;
    ConfiguracionNCF_ESP_FINAL: TFloatField;
    ConfiguracionNO_AUTORIZACION2: TFloatField;
    ConfiguracionNO_AUTORIZACION3: TFloatField;
    ConfiguracionNO_AUTORIZACION: TFloatField;
    ConfiguracionUSAR_CF: TWideStringField;
    ConfiguracionUSAR_VF: TWideStringField;
    ConfiguracionUSAR_ESP: TWideStringField;
    ConfiguracionROTULO_FC: TWideStringField;
    ConfiguracionROTULO_FVF: TWideStringField;
    ConfiguracionROTULO_ESP: TWideStringField;
    ConfiguracionVARIABLE_DEDUCIBLE: TFloatField;
    ConfiguracionLOGO: TBlobField;
    ConfiguracionCLAVEANULAR: TWideStringField;
    ConfiguracionTERMINAL_TPV: TWideStringField;
    ConfiguracionMONTOCF: TFloatField;
    ConfiguracionREDONDEAR: TWideStringField;
    ZdetalleTOTAL: TFloatField;
    ZuConduce: TZUpdateSQL;
    ZDconduce: TZQuery;
    DataSource2: TDataSource;
    ZDconduceDCONDUCEID: TIntegerField;
    ZDconduceMCONDUCEID: TIntegerField;
    ZDconduceCOD_ART: TIntegerField;
    ZDconduceCANDIDAD: TFloatField;
    ZDconduceESTADO: TIntegerField;
    ZDconduceARTICULO: TWideStringField;
    FbqMaster_FactTIENDAID: TIntegerField;
    FbqMaster_FactCONDICIONVENTA: TWideStringField;
    FbtClientesCOMISION: TFloatField;
    FbtClientesNUMEROPIN: TWideStringField;
    Zrecibo_pagoCLIENTEID: TIntegerField;
    Zrecibo_pagoUSUARIOID: TIntegerField;
    Zrecibo_pagoNOMBRE_CLIENTE: TWideStringField;
    ZAjusteM: TZQuery;
    AjusteD: TZQuery;
    zUAsjusteM: TZUpdateSQL;
    SUAjusteD: TZUpdateSQL;
    AjusteDDETALLEID: TIntegerField;
    AjusteDMASTERID: TIntegerField;
    AjusteDCANT: TFloatField;
    AjusteDESTADO: TIntegerField;
    DsMAjuste: TDataSource;
    AjusteDCOD_ART: TIntegerField;
    AjusteDMONTOCOSTO: TFloatField;
    AjusteDTOTALIMP: TFloatField;
    AjusteDTOTALCOSTO: TFloatField;
    ZProveedor: TZQuery;
    ZUproveedor: TZUpdateSQL;
    FbqMaster_FactPINREFERIDO: TWideStringField;
    ZdetalleANCHO: TFloatField;
    ZdetalleALTO: TFloatField;
    ZComboCANTIDAD: TFloatField;
    ZTurno: TZQuery;
    ZUTurno: TZUpdateSQL;
    ZTurnoTURNOID: TIntegerField;
    ZTurnoUSUARIOID: TIntegerField;
    ZTurnoEFECTIVO_INICIAL: TFloatField;
    ZTurnoESTADO: TIntegerField;
    ZTurnoFECHA: TDateField;
    ZTurnoNOMBRES_EMP: TWideStringField;
    ZProveedorCOD_PROV: TIntegerField;
    ZProveedorNOMBRE_PRO: TWideStringField;
    ZProveedorNOM_CONTACTO: TWideStringField;
    ZProveedorDIRECCION: TWideStringField;
    ZProveedorTELF1: TWideStringField;
    ZProveedorTELF2: TWideStringField;
    ZProveedorEMAIL: TWideStringField;
    ZProveedorWEBSITE: TWideStringField;
    ZMDescarga: TZQuery;
    ZUMdescarga: TZUpdateSQL;
    ZMDescargaMDESCARGARID: TIntegerField;
    ZMDescargaFECHA: TDateField;
    ZMDescargaUSUARIOID: TIntegerField;
    ZMDescargaDESCID: TIntegerField;
    ZMDescargaNOMBRES_EMP: TWideStringField;
    ZDdescarga: TZQuery;
    ZUDdescarga: TZUpdateSQL;
    ZDdescargaDDESCARGARID: TIntegerField;
    ZDdescargaMDESCARGARID: TIntegerField;
    ZDdescargaCOD_ART: TIntegerField;
    ZDdescargaCANTIDAD: TFloatField;
    ZDdescargaESTADO: TIntegerField;
    DsMDescarga: TDataSource;
    ZMDescargaDESCRIPCION: TWideStringField;
    ZMDescargaNOTA: TWideMemoField;
    ZDdescargaARTICULO: TWideStringField;
    ZConceptos_Gastos: TZQuery;
    ZuConceptos_Gastos: TZUpdateSQL;
    ZConceptos_GastosCONCEPTOSID: TIntegerField;
    ZConceptos_GastosDESCRIPCION: TWideStringField;
    ZConceptos_GastosESTADO: TIntegerField;
    ZConceptos_GastosC1: TIntegerField;
    ZConceptos_GastosC2: TIntegerField;
    ZConceptos_GastosC3: TIntegerField;
    ZGastos: TZQuery;
    zUgastos: TZUpdateSQL;
    ZGastosGASTOSID: TIntegerField;
    ZGastosFECHA: TDateField;
    ZGastosUSUARIOID: TIntegerField;
    ZGastosCONCEPTOSID: TIntegerField;
    ZGastosNOTA: TWideMemoField;
    ZGastosIMPORTE: TFloatField;
    ZGastosBENEFICIADO: TWideStringField;
    ZGastosESTADO: TIntegerField;
    ZGastosDESCRIPCION: TWideStringField;
    zcaja: TZQuery;
    ZUcaja: TZUpdateSQL;
    zcajaCUADRE1: TIntegerField;
    zcajaFECHA: TDateField;
    zcajaUSAURIOID: TIntegerField;
    zcajaMONTOINICIAL: TFloatField;
    zcajaTOTAL_EFECTIVO: TFloatField;
    zcajaVENTAS: TFloatField;
    zcajaGASTOS: TFloatField;
    zcajaCOBRANZAS: TFloatField;
    zcajaNOTACREDITO: TFloatField;
    zcajaFECTIVO: TFloatField;
    zcajaTARJETA: TFloatField;
    zcajaCHEQUE: TFloatField;
    zcajaESTADO: TIntegerField;
    zcajaNOMBRES_EMP: TWideStringField;
    zcajaTOTAL_GASTOS: TFloatField;
    MNc: TZQuery;
    ZUMNC: TZUpdateSQL;
    MNcMNCID: TIntegerField;
    MNcFECHA: TDateField;
    MNcUSUARIOID: TIntegerField;
    MNcNO_FACT: TIntegerField;
    MNcCLIENTEID: TIntegerField;
    MNcESTADO: TIntegerField;
    MNcNOMBRES_EMP: TWideStringField;
    MNcNOMBRES: TWideStringField;
    MNcAFECTA_INV: TIntegerField;
    MNcAFECTA_CAJA: TIntegerField;
    MNcMONTO: TFloatField;
    MNcOBSERVACION: TWideMemoField;
    DNC: TZQuery;
    ZUDNC: TZUpdateSQL;
    DsMNC: TDataSource;
    FbqMaster_FactNC: TIntegerField;
    MNcCONIDICIONFACT: TWideStringField;
    NCF: TZQuery;
    zuNcf: TZUpdateSQL;
    NCFNCFID: TIntegerField;
    NCFNUNTEXT: TWideStringField;
    NCFDESDE: TIntegerField;
    NCFHASTA: TIntegerField;
    NCFUSO: TIntegerField;
    NCFTIPO: TWideStringField;
    ConfiguracionCOMISIONVENTA: TFloatField;
    ZUconfiguracionCOMISIONVENTA: TFloatField;
    FqArticulosARTICULO: TWideStringField;
    ConfiguracionCONFID: TIntegerField;
    ConfiguracionLOGO_FRONTAR: TBlobField;
    ConfiguracionLOGOF_TXT: TWideStringField;
    ConfiguracionLOGOP_TXT: TWideStringField;
    ZUconfiguracionCONFID: TIntegerField;
    ZUconfiguracionLOGO_FRONTAR: TBlobField;
    ZUconfiguracionLOGOF_TXT: TWideStringField;
    ZUconfiguracionLOGOP_TXT: TWideStringField;
    ConfiguracionINSERTARSERIAL: TIntegerField;
    NCFIDCONFIG: TIntegerField;
    NCFSIGUIENTE: TWideStringField;
    ZUconfiguracionINSERTARSERIAL: TIntegerField;
    ConfiguracionDIRECCION: TWideStringField;
    ZUconfiguracionDIRECCION: TWideStringField;
    SeriesNO_FACT: TIntegerField;
    ConfiguracionMSN_PIE_FACT: TWideStringField;
    ConfiguracionITBIS_D: TFloatField;
    ZUconfiguracionITBIS_D: TFloatField;
    MantArtDESCRIPCIONWEB: TWideMemoField;
    MantArtPUBLICARWEB: TIntegerField;
    ConfiguracionENLACEAWEB: TIntegerField;
    ConfiguracionPISTOLAOPTICA: TIntegerField;
    ZUconfiguracionENLACEAWEB: TIntegerField;
    ZUconfiguracionPISTOLAOPTICA: TIntegerField;
    SeriesIDDETALLE: TIntegerField;
    MantArtARTICULO: TWideStringField;
    Zunidad: TZQuery;
    ZU_Unidad: TZUpdateSQL;
    ZunidadCOD_UNIDAD_M: TIntegerField;
    ZunidadUNIDAD: TWideStringField;
    ZunidadDESCRIPCION: TWideStringField;
    ConfiguracionTIPO_FACTURACION: TIntegerField;
    ZUconfiguracionTIPO_FACTURACION: TIntegerField;
    ConfiguracionEXISTENCIAFACT: TIntegerField;
    ZUconfiguracionEXISTENCIAFACT: TIntegerField;
    Control_Precio: TZQuery;
    Control_PrecioCPID: TIntegerField;
    Control_PrecioNO_ART: TIntegerField;
    Control_PrecioUNIDAD_M: TIntegerField;
    Control_PrecioPRECIO1: TFloatField;
    Control_PrecioPRECIO2: TFloatField;
    Control_PrecioUNIDAD: TWideStringField;
    ZuCP: TZUpdateSQL;
    MantArtEMPAQUE: TIntegerField;
    MantArtCANT_EMPA: TFloatField;
    Control_PrecioPRECIO3: TFloatField;
    MantArtCOD_PROV2: TIntegerField;
    MantArtCOD_PROV3: TIntegerField;
    MantArtREFERENCIA: TWideStringField;
    ZqProv_Arti: TZQuery;
    ZuProv_arti: TZUpdateSQL;
    ZqProv_ArtiPROBEID: TIntegerField;
    ZqProv_ArtiCOD_ART: TIntegerField;
    ZqProv_ArtiREFERENCIA: TWideStringField;
    ZqProv_ArtiPROVEID: TIntegerField;
    ZqProv_ArtiDESCRIPCION: TWideStringField;
    ConfiguracionRUTADB: TWideStringField;
    ZUconfiguracionRUTADB: TWideStringField;
    FbqMaster_FactCODVEN: TIntegerField;
    FbqMaster_FactCAJEROID: TIntegerField;
    ZunidadPOS: TIntegerField;
    ZdetalleUNIDADID: TIntegerField;
    ZdetalleITBS_ART: TWideStringField;
    ZdetalleUNIDAD: TWideStringField;
    ZdetalleEX: TWideStringField;
    FbtClientesTELEFONO3: TWideStringField;
    FbtClientesEMAIL: TWideStringField;
    FbCategoriasIMAGEN: TBlobField;
    FbCategoriasEXTFOTO: TWideStringField;
    MantArtOPCION_SABOR: TWideStringField;
    FbCategoriasOPCION: TWideStringField;
    FbCategoriasCAT: TWideStringField;
    ZqGustos: TZQuery;
    ZUgustos: TZUpdateSQL;
    ZqGustosID_SABOR: TIntegerField;
    ZqGustosIDARTICULO: TIntegerField;
    ZqGustosDESCRIPCION: TWideStringField;
    ZqGustosIMAGEN: TBlobField;
    ZqGustosESTADO: TIntegerField;
    ZqGustosCOD_CAT: TIntegerField;
    ZqGustosSTOCK: TFloatField;
    ZqGustosSTOCK_MIN: TFloatField;
    ZqGustosSTOCK_MAX: TFloatField;
    ZqGustosOP: TIntegerField;
    ZqGustosCOSTOS: TFloatField;
    ZqGustosPRECIO: TFloatField;
    ZqGustosCAT: TWideStringField;
    ZqGustosCOSTO_PROMEDIO: TFloatField;
    MantArtSTOCK_MA: TFloatField;
    MantArtSTOCK_M: TFloatField;
    MantArtFACTOR: TFloatField;
    MantArtTIPO_PRODUCTOS: TWideStringField;
    MantArtFACTURABLE: TIntegerField;
    ZqSaborFact: TZQuery;
    ZUSaborFC: TZUpdateSQL;
    ZqSaborFactID_SF: TIntegerField;
    ZqSaborFactID_FACT: TIntegerField;
    ZqSaborFactFECHA: TDateField;
    ZqSaborFactIDSABOR: TIntegerField;
    ZqSaborFactCOSTO: TFloatField;
    ZqSaborFactCANTIDAD: TFloatField;
    ZqSaborFactPRECIO_VENTA: TFloatField;
    ZqSaborFactOP: TIntegerField;
    ZqSaborFactLINE: TIntegerField;
    ZqSaborFactARTICULO: TWideStringField;
    ZqSaborFactPRODUCTO: TIntegerField;
    IbqEmpleadosIMAGEN: TBlobField;
    ZEmpleadosIMAGEN: TBlobField;
    ZManTurnos: TZQuery;
    ZManTurnosID_TURNOS: TIntegerField;
    ZManTurnosDESCRICPCION: TWideStringField;
    ZManTurnosINICIO: TTimeField;
    ZManTurnosFINAL: TTimeField;
    ZUMturnos: TZUpdateSQL;
    ZTurnoIDTURNO: TIntegerField;
    ZTurnoCAJA: TWideStringField;
    ZTurnoDESCRICPCION: TWideStringField;
    ConfiguracionCANT_CAJA: TIntegerField;
    zcajaESTADO_1: TWideStringField;
    MantArtSTOCK: TFloatField;
    MantArtOPCIONES_BOLA: TWideStringField;
    ZqParticion: TZQuery;
    ZqUPArticionado: TZUpdateSQL;
    MantArtPARTICIONADO: TWideStringField;
    MantArtCOMPUESTO: TWideStringField;
    ConfiguracionTAZA: TFloatField;
    ConfiguracionMONEDA: TWideStringField;
    ConfiguracionAPLICAR_AUMENTO_TAZA: TWideStringField;
    MantArtBENEFICIOS: TFloatField;
    MantArtMONEDA: TWideStringField;
    MantArtUNIDAD: TWideStringField;
    ZTurnoHORA: TTimeField;
    ConfiguracionANCHO_IMG_FRONTAL: TIntegerField;
    ConfiguracionALTO_IMG_FRONTAL: TIntegerField;
    ZUconfiguracionCANT_CAJA: TIntegerField;
    ZUconfiguracionTAZA: TFloatField;
    ZUconfiguracionMONEDA: TWideStringField;
    ZUconfiguracionAPLICAR_AUMENTO_TAZA: TWideStringField;
    ConfiguracionLEFT_IMAGEN: TIntegerField;
    ConfiguracionRIGHT_IMAGEN: TIntegerField;
    ZUconfiguracionANCHO_IMG_FRONTAL: TIntegerField;
    ZUconfiguracionALTO_IMG_FRONTAL: TIntegerField;
    ZUconfiguracionLEFT_IMAGEN: TIntegerField;
    ZUconfiguracionRIGHT_IMAGEN: TIntegerField;
    MantArtTAZA_COMPRA: TFloatField;
    AjusteDMONEDA: TWideStringField;
    ZAjusteMNOID: TIntegerField;
    ZAjusteMFECHA: TDateField;
    ZAjusteMUSUARIOID: TIntegerField;
    ZAjusteMTIENDAID: TIntegerField;
    ZAjusteMCONDICION: TWideStringField;
    ZAjusteMPROVID: TIntegerField;
    ZAjusteMNOFACT: TWideStringField;
    ZAjusteMFECHA_COMPRA: TDateField;
    ZAjusteMPLAZO: TIntegerField;
    ZAjusteMMONTOFACT: TFloatField;
    ZAjusteMMONTOPAGO: TFloatField;
    ZAjusteMMONTOPEND: TFloatField;
    ZAjusteMESTADO: TIntegerField;
    ZAjusteMNOMBRES_EMP: TWideStringField;
    ZAjusteMFECHA_V: TDateField;
    ZAjusteMMONEDA: TWideStringField;
    ZAjusteMCAMBIOMONEDA: TFloatField;
    ZqParticionID: TIntegerField;
    ZqParticionCOD_ARTI: TIntegerField;
    ZqParticionCANTI: TFloatField;
    ZqParticionUNIDAD: TWideStringField;
    ZqParticionCOD_PART: TFloatField;
    ZqParticionID_UNIDAD: TIntegerField;
    ZqParticionDESCRIPCION: TWideStringField;
    ZqParticionPRECIO1: TFloatField;
    ZqParticionPRECIO2: TFloatField;
    ConfiguracionREDONDEOCOMPLETO: TIntegerField;
    ZUconfiguracionREDONDEOCOMPLETO: TIntegerField;
    ZAjusteMFLETE: TFloatField;
    ZAjusteMOTROSGASTOS: TFloatField;
    ZAjusteMDESCUENTO: TFloatField;
    AjusteDPRECIOUNIT: TFloatField;
    ZMantArt1: TZUpdateSQL;
    MantArt1: TZQuery;
    MantArt1COD_ART: TIntegerField;
    MantArt1CODIGOTXT: TWideStringField;
    MantArt1ARTICULO: TWideStringField;
    MantArt1MODELO: TWideStringField;
    MantArt1MARCA: TWideStringField;
    MantArt1COLOR: TWideStringField;
    MantArt1COD_CAT: TIntegerField;
    MantArt1COD_SERIE: TIntegerField;
    MantArt1COD_ALM: TIntegerField;
    MantArt1COSTO: TFloatField;
    MantArt1COD_PROV1: TIntegerField;
    MantArt1EXISTENCIA1: TFloatField;
    MantArt1ABREVIADO: TWideStringField;
    MantArt1COD_BARRA: TWideStringField;
    MantArt1COD_UV: TIntegerField;
    MantArt1USUARIOMOD: TIntegerField;
    MantArt1FECHA_MOD: TDateField;
    MantArt1POLITICA: TWideStringField;
    MantArt1COSTO_PR: TFloatField;
    MantArt1IMAGEN: TBlobField;
    MantArt1CLA_COSTO: TWideStringField;
    MantArt1CLA_PRECIO: TWideStringField;
    MantArt1PRECIO_A: TFloatField;
    MantArt1PRECIO_B: TFloatField;
    MantArt1PRECIO_D: TFloatField;
    MantArt1ESTADO: TIntegerField;
    MantArt1EXTFOTO: TWideStringField;
    MantArt1DESCRIPCIONWEB: TWideMemoField;
    MantArt1PUBLICARWEB: TIntegerField;
    MantArt1CODIGOBARRA: TWideStringField;
    MantArt1EMPAQUE: TIntegerField;
    MantArt1CANT_EMPA: TFloatField;
    MantArt1COD_PROV2: TIntegerField;
    MantArt1COD_PROV3: TIntegerField;
    MantArt1REFERENCIA: TWideStringField;
    MantArt1CONDICION: TIntegerField;
    MantArt1OPCION_SABOR: TWideStringField;
    MantArt1STOCK_MA: TFloatField;
    MantArt1STOCK_M: TFloatField;
    MantArt1FACTOR: TFloatField;
    MantArt1TIPO_PRODUCTOS: TWideStringField;
    MantArt1FACTURABLE: TIntegerField;
    MantArt1STOCK: TFloatField;
    MantArt1OPCIONES_BOLA: TWideStringField;
    MantArt1PARTICIONADO: TWideStringField;
    MantArt1COMPUESTO: TWideStringField;
    MantArt1BENEFICIOS: TFloatField;
    MantArt1MONEDA: TWideStringField;
    MantArt1UNIDAD: TWideStringField;
    MantArt1TAZA_COMPRA: TFloatField;
    ZAjusteMABONO: TFloatField;
    ZAjusteMPAGADO: TFloatField;
    MantArtALMACEN: TIntegerField;
    MalmacenCOD_ALMACEN: TIntegerField;
    MalmacenALM_C: TIntegerField;
    MalmacenDESCRIPCION: TWideStringField;
    MalmacenEXISTENCIA: TFloatField;
    MalmacenCOD_ART: TIntegerField;
    ZInventarioCOD_ALM: TIntegerField;
    ZMDescargaCOD_ALM: TIntegerField;
    ZMDescargaNOMBREALMACEN: TWideStringField;
    ZAjusteMCOD_ALM: TIntegerField;
    ZAjusteMNOMBREALMACEN: TWideStringField;
    zmedicos: TZQuery;
    zmedicosID: TIntegerField;
    zmedicosNOMBREMENDICO: TWideStringField;
    zmedicosTOTALXINTERNAMIENTO: TFloatField;
    zmedicosPORCIENTOANALISIS: TIntegerField;
    zmedicosTOTALPAPA: TFloatField;
    zmedicosTOTALRX: TFloatField;
    ZUmedicos: TZUpdateSQL;
    FbqMaster_FactIDDR: TIntegerField;
    FbqMaster_FactNOMBREDELDR: TWideStringField;
    ZdetalleIDALMACEN: TIntegerField;
    Control_caja: TZQuery;
    ZUControl_Caja: TZUpdateSQL;
    Control_cajaIDCAJA: TIntegerField;
    Control_cajaCAJA_NOMBRE: TWideStringField;
    Control_cajaESTADO: TIntegerField;
    Control_cajaSECUENCIAFACT: TIntegerField;
    Control_cajaNCFID: TIntegerField;
    Control_cajaCONDICION: TWideStringField;
    Control_cajaTABLAARTICULOS: TWideStringField;
    Control_cajaTABLAMASTERFACT: TWideStringField;
    Control_cajaTABLADETALLEFACT: TWideStringField;
    ConsultaCaja: TZReadOnlyQuery;
    ConsultaCajaIDCAJA: TIntegerField;
    ConsultaCajaCAJA_NOMBRE: TWideStringField;
    ConsultaCajaESTADO: TIntegerField;
    ConsultaCajaSECUENCIAFACT: TIntegerField;
    ConsultaCajaNCFID: TIntegerField;
    ConsultaCajaCONDICION: TWideStringField;
    ConsultaCajaTABLAARTICULOS: TWideStringField;
    ConsultaCajaTABLAMASTERFACT: TWideStringField;
    ConsultaCajaTABLADETALLEFACT: TWideStringField;
    ZdetalleBARRA: TWideStringField;
    FbqMaster_FactCAJA: TWideStringField;
    ConfiguracionCOMPROBANTEDEFAULT: TWideStringField;
    ZUconfiguracionCOMPROBANTEDEFAULT: TWideStringField;
    MantArt1ITBIS: TWideStringField;
    ConfiguracionUSOAPLICACION: TWideStringField;
    ZUconfiguracionUSOAPLICACION: TWideStringField;
    FbqMaster_FactNCF_NOMBRE: TWideStringField;
    ConfiguracionARTICULOSVARIOS: TWideStringField;
    ZUconfiguracionARTICULOSVARIOS: TWideStringField;
    ConfiguracionMENSAJE_PIE1: TWideMemoField;
    ConfiguracionMENSAJE_PIE2: TWideMemoField;
    ZUconfiguracionMENSAJE_PIE1: TWideMemoField;
    ZUconfiguracionMENSAJE_PIE2: TWideMemoField;
    ZUconfiguracionIMPRESION_RAPIDA: TWideStringField;
    ZUconfiguracionIMPRESIONDEFECTO: TWideStringField;
    ConfiguracionIMPRESION_RAPIDA: TWideStringField;
    ConfiguracionIMPRESIONDEFECTO: TWideStringField;
    ConfiguracionTEXINICIAR: TWideStringField;
    ZUconfiguracionTEXINICIAR: TWideStringField;
    FbqMaster_FactBONOS: TFloatField;
    zcajaBONOS: TFloatField;
    zcajaCAJA: TWideStringField;
    ConfiguracionLONGTICKET: TIntegerField;
    ZUconfiguracionLONGTICKET: TIntegerField;
    ConfiguracionIMPRIMEOPCIONAL: TWideStringField;
    ZUconfiguracionIMPRIMEOPCIONAL: TWideStringField;
    FbqMaster_FactNUMERO_FACTURA: TFloatField;
    zUCOPIA_ART: TZUpdateSQL;
    COPIA_ART: TZQuery;
    DataSource3: TDataSource;
    COPIA_ARTCOD_ART: TIntegerField;
    COPIA_ARTCODIGOTXT: TWideStringField;
    COPIA_ARTARTICULO: TWideStringField;
    COPIA_ARTMODELO: TWideStringField;
    COPIA_ARTMARCA: TWideStringField;
    COPIA_ARTCOLOR: TWideStringField;
    COPIA_ARTCOD_CAT: TIntegerField;
    COPIA_ARTCOD_SERIE: TIntegerField;
    COPIA_ARTCOD_ALM: TIntegerField;
    COPIA_ARTCOSTO: TFloatField;
    COPIA_ARTCOD_PROV1: TIntegerField;
    COPIA_ARTEXISTENCIA1: TFloatField;
    COPIA_ARTITBIS: TWideStringField;
    COPIA_ARTABREVIADO: TWideStringField;
    COPIA_ARTCOD_BARRA: TWideStringField;
    COPIA_ARTCOD_UV: TIntegerField;
    COPIA_ARTUSUARIOMOD: TIntegerField;
    COPIA_ARTFECHA_MOD: TDateField;
    COPIA_ARTPOLITICA: TWideStringField;
    COPIA_ARTCOSTO_PR: TFloatField;
    COPIA_ARTIMAGEN: TBlobField;
    COPIA_ARTCLA_COSTO: TWideStringField;
    COPIA_ARTCLA_PRECIO: TWideStringField;
    COPIA_ARTPRECIO_A: TFloatField;
    COPIA_ARTPRECIO_B: TFloatField;
    COPIA_ARTPRECIO_D: TFloatField;
    COPIA_ARTESTADO: TIntegerField;
    COPIA_ARTEXTFOTO: TWideStringField;
    COPIA_ARTDESCRIPCIONWEB: TWideMemoField;
    COPIA_ARTPUBLICARWEB: TIntegerField;
    COPIA_ARTCODIGOBARRA: TWideStringField;
    COPIA_ARTEMPAQUE: TIntegerField;
    COPIA_ARTCANT_EMPA: TFloatField;
    COPIA_ARTCOD_PROV2: TIntegerField;
    COPIA_ARTCOD_PROV3: TIntegerField;
    COPIA_ARTREFERENCIA: TWideStringField;
    COPIA_ARTCONDICION: TIntegerField;
    COPIA_ARTOPCION_SABOR: TWideStringField;
    COPIA_ARTSTOCK_MA: TFloatField;
    COPIA_ARTSTOCK_M: TFloatField;
    COPIA_ARTFACTOR: TFloatField;
    COPIA_ARTTIPO_PRODUCTOS: TWideStringField;
    COPIA_ARTFACTURABLE: TIntegerField;
    COPIA_ARTSTOCK: TFloatField;
    COPIA_ARTOPCIONES_BOLA: TWideStringField;
    COPIA_ARTPARTICIONADO: TWideStringField;
    COPIA_ARTCOMPUESTO: TWideStringField;
    COPIA_ARTBENEFICIOS: TFloatField;
    COPIA_ARTMONEDA: TWideStringField;
    COPIA_ARTUNIDAD: TWideStringField;
    COPIA_ARTTAZA_COMPRA: TFloatField;
    COPIA_ARTFECHA_COMPRA: TDateField;
    COPIA_ARTINTERES_ACUMULADO: TFloatField;
    COPIA_ARTALMACEN: TIntegerField;
    FbqMaster_FactOBSERVACIONES: TWideMemoField;
    MantArtCOMISION: TFloatField;
    TbVendedor: TZQuery;
    TbVendedorID: TIntegerField;
    TbVendedorNOMBRE: TWideStringField;
    TbVendedorCEDULA: TWideStringField;
    TbVendedorTELEFONO: TWideStringField;
    TbVendedorESTADO: TIntegerField;
    ZuVEndedores: TZUpdateSQL;
    ConfiguracionENTRAREFECTIVOINICIAL: TWideStringField;
    ZUconfiguracionENTRAREFECTIVOINICIAL: TWideStringField;
    Zsession: TZQuery;
    ZsessionID: TIntegerField;
    ZsessionNOMBRE_SESSION: TWideStringField;
    ZsessionESTADO: TWideStringField;
    ZsessionFACTURACION: TWideStringField;
    ZsessionCOBRAR: TWideStringField;
    ZsessionREPORTES: TWideStringField;
    ZsessionCONSULTAS: TWideStringField;
    ZUsession: TZUpdateSQL;
    FbtClientesRUTA_ID: TIntegerField;
    TbRutas: TZQuery;
    ZURutas: TZUpdateSQL;
    TbRutasID: TIntegerField;
    TbRutasNOMBRE_RUTA: TWideStringField;
    TbRutasIDVENDEDOR: TIntegerField;
    TbRutasNOMBRE: TWideStringField;
    FbqMaster_FactIDRUTA: TIntegerField;
    FbqMaster_FactDIRECCION: TWideStringField;
    ConfiguracionCAJAID: TIntegerField;
    FbqMaster_FactCAJAID: TIntegerField;
    ZUconfiguracionCAJAID: TIntegerField;
    Control_cajaMONTOINICIAL: TFloatField;
    Control_cajaIDCOMPAñIA: TIntegerField;
    ConsultaCajaMONTOINICIAL: TFloatField;
    ConsultaCajaIDCOMPAñIA: TIntegerField;
    DNCDNCID: TIntegerField;
    DNCMNCID: TIntegerField;
    DNCCOD_ART: TIntegerField;
    DNCCANT: TFloatField;
    DNCPRECIO: TFloatField;
    DNCTOTAL: TFloatField;
    DNCESTADO: TIntegerField;
    DNCCONDICION: TWideStringField;
    DNCIDRUTA: TIntegerField;
    DNCFECHA: TDateField;
    DNCARTICULO: TWideStringField;
    FbtClientesREGIONID: TIntegerField;
    FbtClientesPROVINCIAID: TIntegerField;
    FbtClientesMUNICIPIOID: TIntegerField;
    FbtClientesTIPO: TWideStringField;
    MantArtARTICULOS_OMO: TWideStringField;
    MantArtCODIGOUNICO: TWideStringField;
    MantArtEMPRESA: TWideStringField;
    ZdetalleITBIS: TWideStringField;
    AjusteDARTICULOSNOM: TWideStringField;
    ZdetalleIDTECNICO: TIntegerField;
    ConfiguracionUSARCASHDRAWER: TWideStringField;
    ZUconfiguracionUSARCASHDRAWER: TWideStringField;
    ZTurnoEFECTIVOCAJA: TFloatField;
    ZTurnoCOBRANZA: TFloatField;
    ZTurnoTC: TFloatField;
    ZTurnoCHEQUE: TFloatField;
    ZTurnoVALE: TFloatField;
    ZTurnoGASTOS: TFloatField;
    ZTurnoNC: TFloatField;
    ZTurnoTOTALGASTOS: TFloatField;
    ZTurnoTOTALEINGRESO: TFloatField;
    ZTurnoTOTALCUADRE: TFloatField;
    ZTurnoDESCUADRE: TFloatField;
    ZDetalleEfectivo: TZQuery;
    ZDetalleEfectivoID: TIntegerField;
    ZDetalleEfectivoIDTURNO: TIntegerField;
    ZDetalleEfectivoIDNOMINACION: TIntegerField;
    ZDetalleEfectivoCANTIDAD: TIntegerField;
    DsTurno: TDataSource;
    ZuDetalleEfectivo: TZUpdateSQL;
    ZDetalleEfectivoTotal: TCurrencyField;
    ZDetalleEfectivoNOMINACION: TIntegerField;
    ZTurnoTOTALVENTAS: TFloatField;
    QPagoTarjeta: TZQuery;
    QPagoTarjetaID: TIntegerField;
    QPagoTarjetaIDUSUARIO: TIntegerField;
    QPagoTarjetaMASTERID: TIntegerField;
    QPagoTarjetaNO_REFERENCIA: TWideStringField;
    QPagoTarjetaTIPO: TWideStringField;
    QPagoTarjetaCARACTERISTICA: TWideStringField;
    QPagoTarjetaIDTURNO: TIntegerField;
    QPagoTarjetaFECHA: TDateField;
    ZUpagoxtarjeta: TZUpdateSQL;
    QPagoTarjetaESTADO: TIntegerField;
    QPagoCK: TZQuery;
    QPagoCKID: TIntegerField;
    QPagoCKIDMASTER: TIntegerField;
    QPagoCKIDTURNO: TIntegerField;
    QPagoCKMONTO: TFloatField;
    QPagoCKBANCO: TWideStringField;
    QPagoCKNOCK: TIntegerField;
    QPagoCKFECHA: TDateField;
    QPagoCKESTADO: TIntegerField;
    ZUPagoCK: TZUpdateSQL;
    QPagoCKIDUSUARIO: TIntegerField;
    FbqMaster_FactTCREDITO: TFloatField;
    Zrecibo_pagoIDTURNO: TIntegerField;
    MNcIDTURNO: TIntegerField;
    FbqMaster_FactVEFECTIVA: TFloatField;
    ZTurnoTOTALEGRESOS: TFloatField;
    ZGastosTURNOID: TIntegerField;
    AjusteDOBS: TWideStringField;
    ZqProv_ArtiDIRECCION: TWideStringField;
    ZqProv_ArtiTELEFONO: TWideStringField;
    ZqProv_ArtiEMAIL: TWideStringField;
    ZqProv_ArtiCONTACTO: TWideStringField;
    FqArticulosCONDICION: TWideStringField;
    MantArtCONDICION: TWideStringField;
    ZTurnoSOBRANTES: TFloatField;
    ZunidadVALOR: TFloatField;
    QAlmacen: TZQuery;
    QAlmacenID: TIntegerField;
    QAlmacenDESCRIPCION: TWideStringField;
    ZuAlmacen1: TZUpdateSQL;
    MantArtUTILIDAD2: TFloatField;
    MantArtUTILIDAD3: TFloatField;
    MantArtPRECIO_BRUTO1: TFloatField;
    MantArtPRECIO_BRUTO2: TFloatField;
    MantArtPRECIO_BRUTO3: TFloatField;
    MantArtMAYOREO1: TFloatField;
    MantArtMAYOREO2: TFloatField;
    MantArtMAYOREO3: TFloatField;
    ConfiguracionITBS_DEDUCIBLE: TFloatField;
    ZUconfiguracionITBS_DEDUCIBLE: TFloatField;
    MantArtDESCRIPCION: TWideMemoField;
    MantArtCOSTOPROMENO: TFloatField;
    MantArtINTERES_ACUMULADO: TFloatField;
    MantArtPERCIO_COPA: TFloatField;
    MantArtTIENECOMPACTIBILIDAD: TWideStringField;
    MantArtCOMPACTIBLECON: TIntegerField;
    MantArtITBIS: TWideStringField;
    MantArtUBICACION: TWideStringField;
    FbqMaster_FactPAGOXEFECTIVO: TFloatField;
    FbqMaster_FactPAGOXCHEQUE: TFloatField;
    FbqMaster_FactPAGOXTARJETA: TFloatField;
    FbqMaster_FactPAGOXBONO: TFloatField;
    FbtClientesMUSADOS: TFloatField;
    FbtClientesMPENDIENTES: TFloatField;
    IbqEmpleadosESTADOS: TIntegerField;
    IbqEmpleadosTIENDAID: TIntegerField;
    IbqEmpleadosDESCUENTO: TIntegerField;
    ZEmpleadosDESCUENTO: TIntegerField;
    FbqMaster_FactDIR: TWideStringField;
    ZUd: TZUpdateSQL;
    FbqMaster_FactFECHAVENCIMIENTO: TDateField;
    ConfiguracionIMPRIMECOTIZA: TWideStringField;
    ZUconfiguracionIMPRIMECOTIZA: TWideStringField;
    MantArtOBS: TIntegerField;
    MantArtTIPOB: TWideStringField;
    MantArtESTADOCONDICION: TWideStringField;
    FbqMaster_FactCAJERO: TWideStringField;
    MantArtCODIGOBARRA: TWideStringField;
    ZMoneda: TZQuery;
    ZMonedaID: TIntegerField;
    ZMonedaMONEDA: TWideStringField;
    ZMonedaSIGNO: TWideStringField;
    ZuMoneda: TZUpdateSQL;
    MantArtIDMONEDA: TIntegerField;
    Zbancos: TZQuery;
    ZbancosID: TIntegerField;
    ZbancosBANCO: TWideStringField;
    ZuBancos: TZUpdateSQL;
    ZbancosMONEDA: TIntegerField;
    ZbancosSIGNO: TWideStringField;
    ZbancosNO_CTA: TWideStringField;
    ztIPOtRANS: TZQuery;
    ZuTTrans: TZUpdateSQL;
    ztIPOtRANSID: TIntegerField;
    ztIPOtRANSTRANSACION: TWideStringField;
    ZTBanco: TZQuery;
    ZTBancoID: TIntegerField;
    ZTBancoID_TIPOTRANS: TIntegerField;
    ZTBancoTIPO: TWideStringField;
    ZTBancoIDBANCO: TIntegerField;
    ZTBancoMONTO: TFloatField;
    ZTBancoOBSERVACION: TWideMemoField;
    ZTBancoCTA_CONTABLE: TWideStringField;
    ZuTBanco: TZUpdateSQL;
    ZTBancoTRANSACION: TWideStringField;
    ZTBancoBANCO: TWideStringField;
    ZTBancoNO_CTA: TWideStringField;
    ZTBancoFECHA: TDateField;
    FbqMaster_FactNOMBRECLIENTE_PRN: TWideStringField;
    FbtClientesNOMBRES: TWideStringField;
    ZAjusteMALMACEN: TWideStringField;
    MRma: TZQuery;
    MRmaID: TIntegerField;
    MRmaNOORDEN: TIntegerField;
    MRmaFECHA_ENTRADA: TDateField;
    MRmaIDCLIENTE: TIntegerField;
    MRmaIDTECNICO: TIntegerField;
    MRmaHORAENTRADA: TTimeField;
    MRmaNO_SERIAL: TWideStringField;
    MRmaIDTIPOEQUIPO: TIntegerField;
    MRmaIDMARCA: TIntegerField;
    MRmaFALLAEQUIPO: TWideMemoField;
    MRmaOBSERVACIONEQUIPO: TWideMemoField;
    MRmaOBSERVACIONTECNICA: TWideMemoField;
    MRmaFECHA_PROMETIDA: TDateField;
    MRmaESTADO: TWideStringField;
    MRmaMONTO: TFloatField;
    ZuMRma: TZUpdateSQL;
    zTipoEquipos: TZQuery;
    zTipoEquiposID: TIntegerField;
    zTipoEquiposTIPOEQUIPO: TWideStringField;
    ZuTipoEquipos: TZUpdateSQL;
    MRmaNOMBRES: TWideStringField;
    MRmaDIRECCION: TWideStringField;
    MRmaTELEFONO: TWideStringField;
    MRmaNOMBRES_EMP: TWideStringField;
    MRmaTIPOEQUIPO: TWideStringField;
    RMAD: TZQuery;
    RMADID: TIntegerField;
    RMADIDMASTER: TIntegerField;
    RMADIDARTICULO: TIntegerField;
    RMADCANT: TFloatField;
    RMADPRECIO: TFloatField;
    RMADITB: TFloatField;
    RMADTOTAL: TFloatField;
    RMADESTADOS: TIntegerField;
    RMADARTICULO: TWideStringField;
    ZuRMaD: TZUpdateSQL;
    DsRma: TDataSource;
    ConfiguracionUSARRMA: TIntegerField;
    ConfiguracionALMACENRMA: TIntegerField;
    ZUconfiguracionUSARRMA: TIntegerField;
    ZUconfiguracionALMACENRMA: TIntegerField;
    ConfiguracionALMACENNOMBRE: TWideStringField;
    ZUconfiguracionALMACENNOMBRE: TWideStringField;
    RMADARTICULOTXT: TWideStringField;
    ZdetalleTITULOPRN: TWideStringField;
    ConduceM: TZQuery;
    ConduceMID: TIntegerField;
    ConduceMIDCONDUCE: TIntegerField;
    ConduceMFECHA: TDateField;
    ConduceMHORA: TTimeField;
    ConduceMCLIENTES: TWideStringField;
    ConduceMNOFACT: TIntegerField;
    ZUConduceM: TZUpdateSQL;
    DsConduceM: TDataSource;
    ConduceD: TZQuery;
    ConduceDID: TIntegerField;
    ConduceDMASTERID: TIntegerField;
    ConduceDCOD_ART: TIntegerField;
    ConduceDCANTI: TFloatField;
    ConduceDCANT_REST: TFloatField;
    ConduceDCANT_SAL: TFloatField;
    ConduceDPRECIO_ST: TFloatField;
    ConduceDITB: TFloatField;
    ConduceDTOTAL: TFloatField;
    ConduceDESTADO: TIntegerField;
    ConduceDARTICULO: TWideStringField;
    ZUConduceD: TZUpdateSQL;
    ZGastosNOMBRES_EMP: TWideStringField;
    ConduceMESTADO: TIntegerField;
    ZdetalleOP: TWideStringField;
    ComisionInstalador: TZQuery;
    ComisionInstaladorID: TIntegerField;
    ComisionInstaladorID_EMP: TIntegerField;
    ComisionInstaladorID_FACT: TIntegerField;
    ComisionInstaladorMONTOSERVICIO: TFloatField;
    ComisionInstaladorMONTOCOMISION: TFloatField;
    ComisionInstaladorESTADO: TIntegerField;
    ComisionInstaladorFECHA: TDateField;
    ZuComision: TZUpdateSQL;
    NCFTITULO: TWideStringField;
    NCFFECHA_VENC: TDateField;
    FbqMaster_FactFECHA_FINAL: TDateField;
    QNotarios: TZQuery;
    QNotariosCOD_PROV: TIntegerField;
    QNotariosNOMBRE_PRO: TWideStringField;
    QNotariosNOM_CONTACTO: TWideStringField;
    QNotariosDIRECCION: TWideStringField;
    QNotariosTELF1: TWideStringField;
    QNotariosTELF2: TWideStringField;
    QNotariosEMAIL: TWideStringField;
    QNotariosWEBSITE: TWideStringField;
    ZUNotarios: TZUpdateSQL;
    FqArticulosEXISTENCIA1: TExtendedField;
    FqArticulosEXISTENCIA: TFloatField;
    MNcNCF: TWideStringField;
    MNcTIPO_NCF: TWideStringField;
    MNcNFC_AFECTADA: TWideStringField;
    QModulos: TZQuery;
    ZuModulos: TZUpdateSQL;
    QModulosID: TIntegerField;
    QModulosNOMBRE_PANTALLAS: TWideStringField;
    QModulosNOMBRE_FORM: TWideStringField;
    QModulosSECCION: TWideStringField;
    QModulosBOTON: TWideStringField;
    QModulosESTADO: TWideStringField;
    QModulosIDNIVEL: TIntegerField;
    Qperfil: TZQuery;
    ZuPerfil: TZUpdateSQL;
    DsUsuario: TDataSource;
    QperfilID: TIntegerField;
    QperfilNOMBRE_PANTALLAS: TWideStringField;
    QperfilNOMBRE_FORM: TWideStringField;
    QperfilSECCION: TWideStringField;
    QperfilBOTON: TWideStringField;
    QperfilESTADO: TWideStringField;
    QperfilIDNIVEL: TIntegerField;
    QperfilIDMODULO: TIntegerField;
    ZInventarioCOSTO_UN: TIntegerField;
    QperfilSECCION_1: TWideStringField;
    QCalificaciones: TZQuery;
    QCalificacionesID_SABOR: TIntegerField;
    QCalificacionesIDARTICULO: TIntegerField;
    QCalificacionesDESCRIPCION: TWideStringField;
    QCalificacionesIMAGEN: TBlobField;
    QCalificacionesESTADO: TIntegerField;
    QCalificacionesCOD_CAT: TIntegerField;
    QCalificacionesSTOCK: TFloatField;
    QCalificacionesSTOCK_MIN: TFloatField;
    QCalificacionesSTOCK_MAX: TFloatField;
    QCalificacionesOP: TIntegerField;
    QCalificacionesCOSTOS: TFloatField;
    QCalificacionesPRECIO: TFloatField;
    QCalificacionesCOSTO_PROMEDIO: TFloatField;
    ZUCalificaciones: TZUpdateSQL;
    SeriesPRECIO: TFloatField;
    SeriesITBS: TFloatField;
    SeriesTOTAL: TFloatField;
    ZdetalleLINEA: TIntegerField;
    ZdetalleEXIST1: TSingleField;
    ZdetalleLEY: TFloatField;
    SQLCocina: TZQuery;
    SQLCocinaID: TIntegerField;
    SQLCocinaFECHA: TDateField;
    SQLCocinaNO_ORDEN: TIntegerField;
    SQLCocinaHORA: TTimeField;
    SQLCocinaCLIENTE: TWideStringField;
    SQLCocinaORDEN: TWideMemoField;
    SQLCocinaTIEMPO: TIntegerField;
    SQLCocinaTIEMPO_RESTANTA: TTimeField;
    SQLCocinaESTADO: TIntegerField;
    ZUCocina: TZUpdateSQL;
    SqlDCocina: TZQuery;
    SqlDCocinaID: TIntegerField;
    SqlDCocinaNO_ORDEN: TIntegerField;
    SqlDCocinaPRODUCTOS: TWideMemoField;
    SqlDCocinaCANT: TIntegerField;
    SqlDCocinaESTADO: TIntegerField;
    ZUSqlUCocina: TZUpdateSQL;
    DsSqlCocina: TDataSource;
    SQLCocinaMESERO: TWideStringField;
    FbqMaster_FactIDTECNICO: TIntegerField;
    FbqMaster_FactCAJ: TWideStringField;
    ZdetalleADICIONAL: TWideStringField;
    ZdetalleFRACCION: TWideStringField;
    ConfiguracionHABILITARMORA: TWideStringField;
    ZUconfiguracionHABILITARMORA: TWideStringField;
    TPagoCXP: TZQuery;
    TPagoCXPID: TIntegerField;
    TPagoCXPFECHA: TDateField;
    TPagoCXPIDPROV: TIntegerField;
    TPagoCXPMONTOPAGADO: TFloatField;
    TPagoCXPLETRAS: TWideStringField;
    TPagoCXPFORMAPAGO: TWideStringField;
    TPagoCXPNOTRANS: TWideStringField;
    TPagoCXPPAGADOA: TWideStringField;
    TPagoCXPIDBANCO: TIntegerField;
    TPagoCXPIDCUENTA: TIntegerField;
    TPagoCXPFACTURAAFECTADA: TWideStringField;
    TPagoCXPIDFACT: TIntegerField;
    TPagoCXPDESCRIPCION: TWideStringField;
    TPagoCXPTELEFONO: TWideStringField;
    ZuPagoCXP: TZUpdateSQL;
    TPagoCXPNORECIBO: TWideStringField;
    TPagoCXPBANCO: TWideStringField;
    TPagoCXPNO_CTA: TWideStringField;
    TDpagoCxc: TZQuery;
    TDpagoCxcID: TIntegerField;
    TDpagoCxcIDMASTER: TIntegerField;
    TDpagoCxcNO_FACT: TWideStringField;
    TDpagoCxcIDMONEDA: TIntegerField;
    TDpagoCxcMONTO: TFloatField;
    TDpagoCxcMONTOC: TFloatField;
    TDpagoCxcPAGADO: TFloatField;
    TDpagoCxcESTADO: TIntegerField;
    TDpagoCxcMODENA: TWideStringField;
    ZuDPagoCxp: TZUpdateSQL;
    DsPagoCXP: TDataSource;
    ZAjusteMNCF: TWideStringField;
    TPagoCXPCONCEPTOS: TWideStringField;
    ZComboDESC: TWideStringField;
    ZdetalleTAZA_COMPRA: TFloatField;
    ZdetalleITB3: TFloatField;
    FbqMaster_FactTECNICO: TWideStringField;
    FbtClientesPINVIP: TWideStringField;
    FbtClientesPIN: TIntegerField;
    MantArtCOSTO_DOLLARS: TFloatField;
    MantArtCODEQUIVALENCIA: TWideStringField;
    MantArtDESC_EQUIVALENCIA: TWideStringField;
    MantArtCANTEQUIVALENCA: TFloatField;
    ZqAvatar: TZQuery;
    zUAvatar: TZUpdateSQL;
    ZqAvatarID: TIntegerField;
    ZqAvatarIMAGEN: TBlobField;
    ZqAvatarACTIVO: TWideStringField;
    ConfiguracionTIPOINVENTARIO: TWideStringField;
    ZUconfiguracionTIPOINVENTARIO: TWideStringField;
    ZTurnoCOBOSNUEVOS: TFloatField;
    ZTurnoCUBOSUSADOS: TFloatField;
    QCubos: TZQuery;
    QCubosID: TIntegerField;
    QCubosIDTURNO: TIntegerField;
    QCubosIDARTICULO: TIntegerField;
    QCubosCANTIDADINICIAL: TFloatField;
    QCubosCANTIDADFINAL: TFloatField;
    QCubosCANTIDADVENDIDO: TFloatField;
    ZuCubos: TZUpdateSQL;
    QCubosARTICULO: TWideStringField;
    QCubosCN_UN: TFloatField;
    QCubosCU_OZ: TFloatField;
    QCubosCN_UN2: TFloatField;
    QCubosCU_OZ2: TFloatField;
    DsTurnos: TDataSource;
    qcubos2: TZQuery;
    zcubos2: TZUpdateSQL;
    qcubos2ID: TIntegerField;
    qcubos2IDTURNO: TIntegerField;
    qcubos2IDARTICULO: TIntegerField;
    qcubos2CANTIDADINICIAL: TFloatField;
    qcubos2CN_UN: TFloatField;
    qcubos2CU_OZ: TFloatField;
    qcubos2CANTIDADFINAL: TFloatField;
    qcubos2CANTIDADVENDIDO: TFloatField;
    qcubos2CN_UN2: TFloatField;
    qcubos2CU_OZ2: TFloatField;
    qcubos2ARTICULO: TWideStringField;
    QCubosFECHA: TDateField;
    qcubos2FECHA: TDateField;
    Zsolidaridad: TZQuery;
    ZsolidaridadID: TIntegerField;
    ZsolidaridadFECHA: TDateField;
    ZsolidaridadIDFACTURA: TIntegerField;
    ZsolidaridadCEDULA: TWideStringField;
    ZsolidaridadNBAUCHE: TWideStringField;
    ZsolidaridadMFACTURA: TFloatField;
    ZsolidaridadMITBS: TFloatField;
    ZsolidaridadMTOTALFACTURA: TFloatField;
    ZsolidaridadESTADO: TIntegerField;
    ZuSolidaridaridad: TZUpdateSQL;
    ZsolidaridadTARJETA: TWideStringField;
    MantArtFECHA_COMPRA: TDateField;
    MantArtPRE1: TFloatField;
    MantArtPRE2: TFloatField;
    MantArtPRE3: TFloatField;
    MantArtCOSP: TFloatField;
    MantArtCOST: TFloatField;
    MantArtPRECIO_C: TFloatField;
    MantArtCAT: TWideStringField;
    MantArtUTILIDAD4: TFloatField;
    MantArtPRECIO_BRUTO4: TFloatField;
    MantArtMAYOREO4: TFloatField;
    ConfiguracionACTIVARSOLIDARIDAD: TWideStringField;
    ZUconfiguracionACTIVARSOLIDARIDAD: TWideStringField;
    MantArtUTILIDADSOBREITBS: TWideStringField;
    ConfiguracionDSBDIASVENTAS: TIntegerField;
    ZUconfiguracionDSBDIASVENTAS: TIntegerField;
    ConfiguracionPERMISOSALIR: TWideStringField;
    ConfiguracionARTICULOREPETIDO: TWideStringField;
    ZUconfiguracionPERMISOSALIR: TWideStringField;
    ZUconfiguracionARTICULOREPETIDO: TWideStringField;
    ZsolidaridadIDTURNO: TIntegerField;
    ConfiguracionEMUSUARIO: TWideStringField;
    ConfiguracionEMCONTRASENA: TWideStringField;
    ConfiguracionEMASUNTO: TWideStringField;
    ConfiguracionEMDESTINATARIOS: TWideStringField;
    ConfiguracionEMADJUNTO: TWideStringField;
    ZUconfiguracionEMUSUARIO: TWideStringField;
    ZUconfiguracionEMCONTRASENA: TWideStringField;
    ZUconfiguracionEMASUNTO: TWideStringField;
    ZUconfiguracionEMDESTINATARIOS: TWideStringField;
    ZUconfiguracionEMADJUNTO: TWideStringField;
    ConfiguracionENVIAREMAILCUADRE: TWideStringField;
    ZUconfiguracionENVIAREMAILCUADRE: TWideStringField;
    TbIngredientes: TZQuery;
    TbIngredientesID: TIntegerField;
    TbIngredientesIDARTI: TIntegerField;
    TbIngredientesINGREDIENTES: TWideStringField;
    TbIngredientesESTADO: TIntegerField;
    ZUingredientes: TZUpdateSQL;
    ZuDingredientes: TZUpdateSQL;
    rbDIngredientes: TZQuery;
    rbDIngredientesID: TIntegerField;
    rbDIngredientesIDARTICULOS: TIntegerField;
    rbDIngredientesIDDETALLE: TIntegerField;
    rbDIngredientesIDMASTER: TIntegerField;
    rbDIngredientesOP: TIntegerField;
    rbDIngredientesINGREDIENTES: TWideStringField;
    rbDIngredientesSELECCION: TWideStringField;
    ConfiguracionCALLE: TWideStringField;
    ConfiguracionSECTOR: TWideStringField;
    ConfiguracionCIUDAD: TWideStringField;
    ZUconfiguracionCALLE: TWideStringField;
    ZUconfiguracionSECTOR: TWideStringField;
    ZUconfiguracionCIUDAD: TWideStringField;
    QCorteInventario: TZQuery;
    DsCorteInventario: TDataSource;
    ZuCorteInventario: TZUpdateSQL;
    QCorteInventarioID: TIntegerField;
    QCorteInventarioFECHA_CORTE: TDateField;
    QCorteInventarioIDUSAURIO: TIntegerField;
    QCorteInventarioMONTO: TFloatField;
    QCorteInventarioCOD_ART: TIntegerField;
    QCorteInventarioEXISTENCIA: TFloatField;
    QCorteInventarioIDMASTER: TIntegerField;
    QCorteInventarioARTICULO: TWideStringField;
    QCorteInventarioRECONTEO: TFloatField;
    SQLCocinaMASTERID: TIntegerField;
    SqlDCocinaIDMASTER: TIntegerField;
    rbDIngredientesNO_ORDEN: TIntegerField;
    FbqMaster_FactIDESTACION: TIntegerField;
    ConfiguracionTIMPRESIONPRE: TIntegerField;
    ZUconfiguracionTIMPRESIONPRE: TIntegerField;
    QcopiaControl: TZQuery;
    QcopiaControlNO_FACT: TIntegerField;
    QcopiaControlFECHA_FAC: TDateField;
    QcopiaControlTIPO: TWideStringField;
    QcopiaControlCOD_CLIENT: TWideStringField;
    QcopiaControlCOD_EMP: TWideStringField;
    QcopiaControlNO_FACT1: TWideStringField;
    QcopiaControlMONTO: TExtendedField;
    QcopiaControlHORA: TTimeField;
    QcopiaControlPOGXITBS: TExtendedField;
    QcopiaControlTIPOPAGO: TWideStringField;
    QcopiaControlMONTOPAGO: TExtendedField;
    QcopiaControlCONDICION: TWideStringField;
    QcopiaControlRENTA: TWideStringField;
    QcopiaControlCODIGO: TIntegerField;
    QcopiaControlTIPOITBS: TWideStringField;
    QcopiaControlVENDEDOR: TWideStringField;
    QcopiaControlSITUACION: TWideStringField;
    QcopiaControlCAJERO: TWideStringField;
    QcopiaControlNCF: TWideStringField;
    QcopiaControlRNC_CLIENTE: TWideStringField;
    QcopiaControlNCF1: TFloatField;
    QcopiaControlNOM_CLIENTE: TWideStringField;
    QcopiaControlDESCUENTO: TFloatField;
    QcopiaControlROTULO: TWideStringField;
    QcopiaControlNO_AUTORIZA_NCF: TFloatField;
    QcopiaControlMONTOFINANCIADO: TFloatField;
    QcopiaControlCUOTAS: TIntegerField;
    QcopiaControlINTERES: TFloatField;
    QcopiaControlDIRECCION: TWideStringField;
    QcopiaControlPAGADO: TFloatField;
    QcopiaControlLEYPROPINA: TFloatField;
    QcopiaControlCOMPROBANTE: TWideStringField;
    QcopiaControlTERMINAL: TWideStringField;
    QcopiaControlEFECTIVO: TFloatField;
    QcopiaControlDEVOLUCION1: TFloatField;
    QcopiaControlRESTANTE: TFloatField;
    QcopiaControlABONO: TFloatField;
    QcopiaControlCHEK: TWideStringField;
    QcopiaControlNO_RECIBO: TIntegerField;
    QcopiaControlPAGADOCXC: TFloatField;
    QcopiaControlMESES: TIntegerField;
    QcopiaControlDIAS: TIntegerField;
    QcopiaControlPENDIENTE: TFloatField;
    QcopiaControlESTADOPAGO: TWideStringField;
    QcopiaControlDEVOLUCION: TFloatField;
    QcopiaControlCONDICION_PAGO: TIntegerField;
    QcopiaControlFECHAVENCIMIENTO: TWideStringField;
    QcopiaControlCOMBO: TWideStringField;
    QcopiaControlCOBRADO: TIntegerField;
    QcopiaControlQUEES: TWideStringField;
    ZUCopiaControl: TZUpdateSQL;
    ConfiguracionVERSION: TIntegerField;
    ConfiguracionCONTROLCONTADOR: TWideStringField;
    ConfiguracionCONTROLCONTADORTOTAL: TIntegerField;
    QVersion25: TZReadOnlyQuery;
    ZUconfiguracionVERSION: TIntegerField;
    ZUconfiguracionCONTROLCONTADOR: TWideStringField;
    ZUconfiguracionCONTROLCONTADORTOTAL: TIntegerField;
    ConfiguracionCLAVEAUTORIZACION: TWideStringField;
    ZUconfiguracionCLAVEAUTORIZACION: TWideStringField;
    QInventarioEQ: TZReadOnlyQuery;
    qCodMin: TZReadOnlyQuery;
    MantArtAPLICARPORMAYOR: TWideStringField;
    QInventarioEQCOD_ART: TIntegerField;
    QInventarioEQARTICULO: TWideStringField;
    QInventarioEQCANTIDADEQUIVALENCIA: TExtendedField;
    QInventarioEQEXISTENCIA: TExtendedField;
    QInventarioEQEQ: TWideStringField;
    QInventarioEQUNIDAD: TWideStringField;
    QInventarioEQALMACEN: TWideStringField;
    qCodMinCODIGOMINIMO: TIntegerField;
    qCodMinCANTEQUIVALENCA: TExtendedField;
    qCodMinCANTEMP: TExtendedField;
    QImpuestos: TZQuery;
    zUImpuestos: TZUpdateSQL;
    QImpuestosID: TIntegerField;
    QImpuestosDESCRIPCION: TWideStringField;
    QImpuestosABREVIADO: TWideStringField;
    QImpuestosIMP: TExtendedField;
    QImpuestosESTADO: TWideStringField;
    MantArtNOM_INDICACION: TWideStringField;
    MantArtSUST: TWideStringField;
    MantArtMARCAS: TWideStringField;
    MantArtNOMBRE_PRO: TWideStringField;
    MantArtCLASI: TWideStringField;
    MantArtSUBCAT: TWideStringField;
    MantArtNOMBREABREVIADO: TWideStringField;
    MantArtPRESENTACION: TWideStringField;
    MantArtCAPACIDAD: TIntegerField;
    MantArtMODIUSO: TWideStringField;
    MantArtIDMARCA: TIntegerField;
    MantArtDESCPERMITIDO: TIntegerField;
    MantArtSUBCATEGORIA: TIntegerField;
    MantArtSUSTANCIA: TIntegerField;
    MantArtCLASIFICACION: TIntegerField;
    MantArtINDICACION: TIntegerField;
    MantArtUNIDADVENTA: TWideStringField;
    MantArtUNIDADCOMPRA: TWideStringField;
    MantArtSIGNO: TWideStringField;
    MantArtPRO2: TWideStringField;
    MantArtSERIE: TWideStringField;
    MantArtLOTE: TWideStringField;
    MantArtPERMITIRDESC: TWideStringField;
    qSubCategorias: TZQuery;
    ConfiguracionLOTE: TWideStringField;
    ConfiguracionTIPOSALIDALOTE: TWideStringField;
    ZUconfiguracionLOTE: TWideStringField;
    ZUconfiguracionTIPOSALIDALOTE: TWideStringField;
    qSubCategoriasID: TIntegerField;
    qSubCategoriasSUBCATEGORIA: TWideStringField;
    qSubCategoriasIDCATEGORIA: TIntegerField;
    qSubCategoriasCAT: TWideStringField;
    zuSubCategorias: TZUpdateSQL;
    qSustancia: TZQuery;
    ZuSustancia: TZUpdateSQL;
    qSustanciaID: TIntegerField;
    qSustanciaSUSTANCIA: TWideStringField;
    QMarca: TZQuery;
    zuMarca: TZUpdateSQL;
    QMarcaID: TIntegerField;
    QMarcaMARCAS: TWideStringField;
    QMarcaIDPROV: TIntegerField;
    qIndicaciones: TZQuery;
    zuIndicaciones: TZUpdateSQL;
    qIndicacionesID: TIntegerField;
    qIndicacionesNOM_INDICACION: TWideStringField;
    qClasificación: TZQuery;
    zuClasificacion: TZUpdateSQL;
    qClasificaciónID: TIntegerField;
    qClasificaciónCLASIFICACION: TWideStringField;
    MantArtIDIMPUESTO: TIntegerField;
    ConfiguracionTIPOPRECIO: TWideStringField;
    ZUconfiguracionTIPOPRECIO: TWideStringField;
    ZDdescargaSERIE: TIntegerField;
    ZDdescargaLOTE: TWideStringField;
    ZDdescargaFV: TDateField;
    ZDdescargaCODIGOBARRA: TWideStringField;
    ZDdescargaPRECIO: TFloatField;
    ZDdescargaTOTAL: TFloatField;
    ZDdescargaCOSTO: TFloatField;
    ZDdescargaIMPUESTO: TFloatField;
    ZDdescargaID: TIntegerField;
    QMlote: TZQuery;
    zuMelote: TZUpdateSQL;
    ZDdescargaEXX: TFloatField;
    QMloteID: TIntegerField;
    QMloteIDARTICULO: TIntegerField;
    QMloteNO_LOTE: TWideStringField;
    QMloteFV: TDateField;
    QMloteEXIS_INI: TFloatField;
    QMloteCANT: TFloatField;
    QMloteESTADO: TIntegerField;
    QInventarioLote: TZQuery;
    zuInventarioLote: TZUpdateSQL;
    QInventarioLoteID: TIntegerField;
    QInventarioLoteFECHA_INICIAL: TDateField;
    QInventarioLoteFECHA_CIERRE: TDateField;
    QInventarioLoteMONTO: TFloatField;
    QInventarioLoteESTADO: TWideStringField;
    qConsultarInvetarioLote: TZReadOnlyQuery;
    qConsultarInvetarioLoteID: TIntegerField;
    qConsultarInvetarioLoteFECHA_INICIAL: TDateField;
    qConsultarInvetarioLoteFECHA_CIERRE: TDateField;
    qConsultarInvetarioLoteMONTO: TFloatField;
    qConsultarInvetarioLoteESTADO: TWideStringField;
    ZDdescargaLIN: TIntegerField;
    QMloteLIN: TIntegerField;
    ZdetalleLIN: TIntegerField;
    ZInventarioLIN: TIntegerField;
    ZdetalleUNID: TWideStringField;
    FbqMaster_FactSUBTOTAL: TFloatField;
    ZdetallePORCENTDESC: TFloatField;
    ZdetalleDESC: TFloatField;
    ZdetalleIBSAPLICADO: TFloatField;
    AjusteDLIN: TIntegerField;
    AjusteDFV: TDateField;
    AjusteDLOTE: TWideStringField;
    zProductosFiltro: TZReadOnlyQuery;
    zProductosFiltroID: TIntegerField;
    zProductosFiltroCRITERIO: TWideStringField;
    zProductosFiltroTEXTO: TWideStringField;
    zProductosFiltroESTADO: TWideStringField;
    FbqFabricantesCOD_PROV: TIntegerField;
    FbqFabricantesNOMBRE_PRO: TWideStringField;
    FbqFabricantesNOM_CONTACTO: TWideStringField;
    FbqFabricantesDIRECCION: TWideStringField;
    FbqFabricantesTELF1: TWideStringField;
    FbqFabricantesTELF2: TWideStringField;
    FbqFabricantesEMAIL: TWideStringField;
    FbqFabricantesWEBSITE: TWideStringField;
    FbqFabricantesTEL_EXTENSION: TIntegerField;
    FbqFabricantesFAX: TWideStringField;
    FbqFabricantesRNC: TWideStringField;
    FbqFabricantesV_CELULAR: TWideStringField;
    ZAjusteMNOMBRE_PRO: TWideStringField;
    ZUsauriosUSUARIOID: TIntegerField;
    ZUsauriosEMPLEADOID: TIntegerField;
    ZUsauriosTIPO: TIntegerField;
    ZUsauriosPASSW: TWideStringField;
    ZUsauriosIDAC: TWideStringField;
    ZUsauriosIDSESSION: TIntegerField;
    ZUsauriosESTADO1: TWideStringField;
    ZUsauriosDESCUENTO: TIntegerField;
    ZUsauriosSEXO: TWideStringField;
    ZUsauriosAVATAR: TBlobField;
    ZUsauriosNOMBRES_EMP: TWideStringField;
    ZUsauriosTIENDAID: TIntegerField;
    ZUsauriosNOMBRE_SESSION: TWideStringField;
    ZqUsuariosUSUARIOID: TIntegerField;
    ZqUsuariosEMPLEADOID: TIntegerField;
    ZqUsuariosTIPO: TIntegerField;
    ZqUsuariosPASSW: TWideStringField;
    ZqUsuariosIDAC: TWideStringField;
    ZqUsuariosIDSESSION: TIntegerField;
    ZqUsuariosESTADO1: TWideStringField;
    ZqUsuariosDESCUENTO: TIntegerField;
    ZqUsuariosSEXO: TWideStringField;
    ZqUsuariosAVATAR: TBlobField;
    ZqUsuariosNOMBRES_EMP: TWideStringField;
    ZqUsuariosTIENDAID: TIntegerField;
    ZqUsuariosNOMBRE_SESSION: TWideStringField;
    ZdetallePORCDESCUENTO: TFloatField;
    FbqMaster_FactESTACION: TWideStringField;
    procedure DataModuleCreate(Sender: TObject);

 //   procedure zdetalle1BeforeInsert(DataSet: TDataSet);
 //   procedure zdetalle1BeforeOpen(DataSet: TDataSet);
 //   procedure zdetalle1AfterInsert(DataSet: TDataSet);
    procedure zdetalle1AfterPost(DataSet: TDataSet);
    procedure zdetalle1BeforePost(DataSet: TDataSet);
    procedure ZDetalleEfectivoCalcFields(DataSet: TDataSet);
    procedure FbqMaster_FactPostError(DataSet: TDataSet; E: EDatabaseError;
      var Action: TDataAction);

      procedure TratarExcepciones (sender: tObject; E : Exception);
    procedure RMADCalcFields(DataSet: TDataSet);
    procedure ConduceDCalcFields(DataSet: TDataSet);
    procedure SeriesBeforeDelete(DataSet: TDataSet);

  private

     procedure actualizaversiones;
    { Private declarations }
  public

    { Public declarations }
  end;

var
  datos: Tdatos;
  IniFile, Usuario, UsuarioActivo: String;

implementation
uses tools, Unit8, Pizeria;
{$R *.dfm}

procedure Tdatos.actualizaversiones;
begin

// Version 25


end;

procedure Tdatos.ConduceDCalcFields(DataSet: TDataSet);
begin
datos.ConduceDCANT_REST.Value := datos.ConduceDCANT_REST.Value - datos.ConduceDCANT_SAL.Value;

end;

procedure Tdatos.DataModuleCreate(Sender: TObject);
begin

if FileExists(ChangeFileExt(Application.ExeName,'.ini')) then
      begin
         try
             IniFile := ChangeFileExt(Application.ExeName,'.ini');
             data.Connected := False;
             data.Database := ReadString_Ini(IniFile,'Database', 'Ruta','');
             data.HostName := ReadString_Ini(IniFile,'Database', 'HostName','');
             datos.data.Properties.Add('PAGE_SIZE 4096 DEFAULT CHARACTER SET ISO8859_1');
             data.Connected := true;


//             IniFile := ChangeFileExt(Application.ExeName,'.ini');
//             data1.Connected := False;
//             data1.Database := ReadString_Ini(IniFile,'Database1', 'Ruta','');
//             data1.HostName := ReadString_Ini(IniFile,'Database1', 'HostName','');
//             datos.data1.Properties.Add('PAGE_SIZE 4096 DEFAULT CHARACTER SET ISO8859_1');
//             data1.Connected := true;


           //  Control;
         except
             on E: Exception do
      	    begin
               MsgError('Se produjo el siguiente error al ejecutar la aplicación'#13+
      	               '**** '+E.Message+'****'#13+
                        'Esto provoca que no se pueda iniciar,'+
                        'Si el problema persiste, llamar al soporte');
               Application.Terminate;
             end;
         end;
       end
    else begin
      MsgError('El Archivo de configuracion de la aplicación no existe, llamar al soporte!!'#13+
               #9'La aplicacion cargara la base de datos local');
end;



DATOS.Data.Connected := true;
//datos.FbtClientes.Open;
//datos.IbqCategorias.Open;



// if datos.ZUconfiguracion.FindField('Version') = Nil then
//   begin
////    with QVersion25 do
////       begin
////         close;
////         sql.Clear;
////         sql.Add('alter table configuracion');
////         sql.Add('add version integer, add CONTROLCONTADOR varchar(2), add CONTROLCONTADORTOTAL integer');
////
////         ExecSQL;
////        end;
////
////         datos.data.Commit;
//////    with QVersion25 do
//////       begin
//////         close;
//////         sql.Clear;
//////         sql.Add('update configuracion set version = 25, CONTROLCONTADOR =''SI'', CONTROLCONTADORTOTAL = 5000');
//////         ExecSQL;
//////        end;
//////
//////       datos.data.Commit;
//
//   end;
//


        datos.ZUconfiguracion.Open;
        datos.ZUconfiguracion.First;



//******** Articulos  *******************
//datos.FqArticulos.Open;
//datos.IbqCategorias.Open;
//datos.FbqFabricantes.Open;
//datos.tienda.Open;
///**************************************

end;

procedure Tdatos.FbqMaster_FactPostError(DataSet: TDataSet; E: EDatabaseError;
  var Action: TDataAction);
begin
// if e is EZDatabaseError then
//  begin
//    case EZDatabaseError(E).ErrorCode of
//      1062 : begin
//        MessageDlg(E.Message + 'La pregunta',mtInformation,[mbYes, mbNo],0);
//
//      end;
//     else
//        MessageDlgS('Se ha producido un error al intentar guardar el registro:' +
//            chr(13) + chr(13) + inttostr(EZDatabaseError(E).ErrorCode) +
//            ' -> ' + E.Message);
//    end;
//    Action := daAbort;
//  end;
end;

procedure Tdatos.RMADCalcFields(DataSet: TDataSet);
begin
datos.RMADTOTAL.Value := datos.RMADPRECIO.Value * datos.RMADCANT.Value;

end;

procedure Tdatos.SeriesBeforeDelete(DataSet: TDataSet);
var
suma : Currency;
itbs : Currency;
descc : Currency;

begin

                                 datos.Zdetalle.Edit;

                                     if FrmPizeria.IbqRArticulosITBIS.Value = 'Si'  then
                                               begin

                                                 datos.ZdetallePRECIO.Value := datos.ZdetallePRECIO.Value - datos.SeriesPRECIO.Value;
                                                 datos.ZdetalleIMPUESTO.Value := datos.ZdetallePRECIO.Value * datos.ZdetalleCANTIDAD.Value;
                                                 datos.ZdetalleITBS.Value   := datos.ZdetalleITBS.Value - datos.Seriesitbs.Value;
                                                 datos.ZdetalleTOTAL.Value    := datos.ZdetalleIMPUESTO.Value + datos.ZdetalleITBS.Value ;



                                                 datos.zdetalle.First;

                                                    while not datos.zdetalle.Eof do
                                                     begin
                                                        suma := (suma + datos.zdetalle.FieldByname('total').Value); //* data.ibtdetallefactCANTIDAD.AsInteger;
                                                        itbs := (itbs + datos.zdetalle.FieldByname('itbs').Value); //* data.ibtdetallefactCANTIDAD.AsInteger;
                                                        descc := (descc + datos.zdetalle.FieldByName('itbis2').Value);
                                                        datos.zdetalle.Edit;
                                                        datos.zdetalletotal.Value   := datos.zdetalletotal.Value;
                                                        datos.ZdetalleITBS.Value    := datos.ZdetalleITBS.Value;
                                                        datos.ZdetalleANCHO.Value   := datos.zdetalleancho.Value;
                                                        datos.ZdetalleITBIS2.Value  := datos.ZdetalleITBIS2.Value;

                                                     datos.zdetalle.Next;

                                               end;


                                            datos.FbqMaster_Fact.Edit;
                                            datos.FbqMaster_Factdescuento.Value := (suma - itbs) * 0.10;
                                            datos.FbqMaster_FactPOGXITBS.Value := itbs;

                                               datos.FbqMaster_FactMONTO.Value := suma - itbs;
                                               datos.FbqMaster_FactMONTOPAGO.Value := datos.FbqMaster_FactMONTO.Value + itbs;


                                           end;




                                           if FrmPizeria.IbqRArticulosITBIS.Value = 'No'  then begin


                                                 datos.ZdetallePRECIO.Value := datos.ZdetallePRECIO.Value - datos.SeriesPRECIO.Value;
                                                 datos.ZdetalleIMPUESTO.Value := datos.ZdetallePRECIO.Value * datos.ZdetalleCANTIDAD.Value;
                                                 datos.ZdetalleITBS.Value   := datos.ZdetalleITBS.Value - datos.Seriesitbs.Value;
                                                 datos.ZdetalleTOTAL.Value    := datos.ZdetalleIMPUESTO.Value + datos.ZdetalleITBS.Value ;


                                                 datos.zdetalle.First;

                                                    while not datos.zdetalle.Eof do
                                                     begin
                                                        suma := (suma + datos.zdetalle.FieldByname('total').Value); //* data.ibtdetallefactCANTIDAD.AsInteger;
                                                        itbs := (itbs + datos.zdetalle.FieldByname('itbs').Value); //* data.ibtdetallefactCANTIDAD.AsInteger;       .
                                                        descc := (descc + datos.zdetalle.FieldByName('itbs2').Value);
                                                        datos.zdetalle.Edit;
                                                        datos.zdetalletotal.Value := datos.zdetalletotal.Value;
                                                        datos.ZdetalleITBS.Value  := datos.ZdetalleITBS.Value;
                                                        datos.ZdetalleANCHO.Value := datos.ZdetalleANCHO.Value;
                                                        datos.ZdetalleITBIS2.Value  := datos.ZdetalleITBIS2.Value;

                                                     datos.zdetalle.Next;

                                              end;

                                            datos.FbqMaster_Fact.Edit;
                                            datos.FbqMaster_Factdescuento.Value :=descc;
                                            datos.FbqMaster_FactPOGXITBS.Value := itbs;




                                            datos.FbqMaster_FactMONTO.Value := suma - itbs;

                                               if datos.FbqMaster_FactDESCUENTO.Value = 0.00 then begin
                                                  datos.FbqMaster_FactMONTOPAGO.Value := datos.FbqMaster_FactMONTO.Value + itbs;
                                                  end else begin
                                                      datos.FbqMaster_FactMONTOPAGO.Value := (datos.FbqMaster_FactMONTO.Value ) + itbs;
                                                  end;

                                        end;
end;

procedure Tdatos.TratarExcepciones(sender: tObject; E: Exception);
Var
  codigo_error  : Integer;
  str_codigo_er : String;
  str_Mensaje   : String;
begin


end;



procedure Tdatos.zdetalle1AfterPost(DataSet: TDataSet);
var
suma : currency;
begin



end;




procedure Tdatos.zdetalle1BeforePost(DataSet: TDataSet);
var
suma : Currency;
begin

end;





procedure Tdatos.ZDetalleEfectivoCalcFields(DataSet: TDataSet);
begin
//zdetalleEfectivo.Edit;
zdetalleEfectivoTotal.Value := ZdetalleEfectivoNominacion.AsInteger * zdetalleEfectivocantidad.AsInteger;
end;


end.
